-- pg_semantic_platform extension upgrade: 0.1.2 -> 0.1.3
-- Generated by `deno task extension` from migrations added since 0.1.2.
-- DO NOT EDIT MANUALLY.

-- =====================================================
-- _versions tracking table (run-once migration guard)
-- =====================================================
-- Created before the migration bodies so _core/0050's
-- `CREATE POLICY ... ON _versions` can attach. The migrate
-- runner creates this via ensureVersionsTable(); CREATE
-- EXTENSION must emit it itself.
CREATE TABLE IF NOT EXISTS _versions (
  name TEXT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_versions_name ON _versions(name);

ALTER TABLE _versions ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- _core/0250_webhook_receiver
-- =====================================================
-- =====================================================
-- WEBHOOK RECEIVER TABLES
-- =====================================================
-- Create tables for webhook receivers and webhook receiver logs
-- These tables are created by inserting into the entities and fields tables
-- =====================================================

-- =====================================================
-- CREATE webhook_receivers TABLE
-- =====================================================

INSERT INTO entities (
    table_name, 
    singular, 
    singular_label, 
    plural_label, 
    description, 
    module_id, 
    view_permission, 
    edit_permission, 
    id_column, 
    label_column
)
VALUES (
    'webhook_receivers',
    'webhook_receiver',
    'Webhook Receiver',
    'Webhook Receivers',
    'Configuration for webhook endpoints',
    1, -- _core module
    'admin',
    'admin',
    'id',
    'label'
);

-- Pre-create table_name as TEXT before inserting the field metadata.
-- The 'parent' format normally maps to INTEGER in format_to_data_type(), which is designed
-- for auto-incrementing ID references. Here we need TEXT because entities.table_name is TEXT
-- (not an auto-incrementing INTEGER id). By pre-creating the column as TEXT, the DD trigger's
-- ADD COLUMN IF NOT EXISTS silently skips creation and proceeds to build the FK TEXT→TEXT.
ALTER TABLE webhook_receivers ADD COLUMN IF NOT EXISTS table_name TEXT NOT NULL DEFAULT '';

-- Add fields to webhook_receivers table
INSERT INTO fields (table_name, field_name, title, format, is_pk, field_order, input_type, width, description, default_value, enum_values, reference_table, reference_delete_mode, relationship_label)
VALUES
    ('webhook_receivers', 'table_name',   'Table',              'reference', FALSE, 10, 'default', 'default', 'Target table for webhook data',                           '',     NULL,                          'entities', 'cascade', 'has receivers'),
    ('webhook_receivers', 'description',  'Description',        'text',      FALSE, 20, 'default', 'w',       'Description of webhook receiver purpose',                 '',     NULL,                          '',         '',        ''),
    ('webhook_receivers', 'auth_type',    'Authentication Type','enum',      FALSE, 30, 'default', 'default', 'Type of authentication (none, hmac, or custom header)',   'none', '["none", "hmac", "header"]'::jsonb, '', '',   ''),
    ('webhook_receivers', 'secret',       'Secret',             'text',      FALSE, 40, 'default', 'default', 'Secret for webhook authentication',                       '',     NULL,                          '',         '',        ''),
    ('webhook_receivers', 'header_name',  'Header Name',        'text',      FALSE, 45, 'default', 'default', 'Custom header name for authentication',                   '',     NULL,                          '',         '',        ''),
    ('webhook_receivers', 'header_value', 'Header Value',       'text',      FALSE, 46, 'default', 'default', 'Expected value for custom header authentication',         '',     NULL,                          '',         '',        ''),
    ('webhook_receivers', 'jsonata',      'JSONata Expression', 'jsonata',   FALSE, 50, 'default', 'w',       'Optional JSONata expression to transform incoming data',  '',     NULL,                          '',         '',        '');

-- =====================================================
-- CREATE webhook_receiver_logs TABLE
-- =====================================================

INSERT INTO entities (
    table_name, 
    singular, 
    singular_label, 
    plural_label, 
    description, 
    module_id, 
    view_permission, 
    edit_permission, 
    id_column, 
    label_column
)
VALUES (
    'webhook_receiver_logs',
    'webhook_receiver_log',
    'Webhook Receiver Log',
    'Webhook Receiver Logs',
    'Log of webhook receiver events',
    1, -- _core module
    'admin',
    'admin',
    'id',
    'label'
);

-- Add fields to webhook_receiver_logs table
-- Note: 'label' is the label_column and is automatically created by the create_dd_table trigger
-- webhook_id is an explicit parent reference to webhook_receivers (ON DELETE CASCADE)
INSERT INTO fields (table_name, field_name, title, format, is_pk, field_order, input_type, width, description, default_value, enum_values, ctype, reference_table, reference_delete_mode, relationship_label)
VALUES
    ('webhook_receiver_logs', 'webhook_id',          'Webhook Receiver',    'parent',    FALSE,  5, 'default', 'default', 'Parent webhook receiver this log belongs to',     NULL,                 NULL,                        NULL, 'webhook_receivers', 'cascade', 'has logs'),
    ('webhook_receiver_logs', 'webhook_receiver_id', 'Webhook Receiver',    'reference', FALSE, 10, 'default', 'default', 'Reference to webhook receiver configuration',      NULL,                 NULL,                        NULL, 'webhook_receivers', 'clear',   'has logs'),
    ('webhook_receiver_logs', 'webhook_timestamp',   'Webhook Timestamp',   'date-time', FALSE, 30, 'default', 'default', 'Timestamp from webhook source',                    NULL,                 NULL,                        NULL, '',                  '',        ''),
    ('webhook_receiver_logs', 'received_timestamp',  'Received Timestamp',  'date-time', FALSE, 40, 'disabled','default', 'Timestamp when webhook was received',              'CURRENT_TIMESTAMP',  NULL,                        NULL, '',                  '',        ''),
    ('webhook_receiver_logs', 'payload',             'Payload',             'json',      FALSE, 50, 'default', 'w',       'Webhook payload data',                             NULL,                 NULL,                        NULL, '',                  '',        ''),
    ('webhook_receiver_logs', 'result',              'Result',              'enum',      FALSE, 60, 'default', 'default', 'Processing result: 10=received, 20=processed, 90=failed', '10',          '["10", "20", "90"]'::jsonb, NULL, '',                  '',        ''),
    ('webhook_receiver_logs', 'error_message',       'Error Message',       'text',      FALSE, 70, 'default', 'w',       'Error message if processing failed',               '',                   NULL,                        NULL, '',                  '',        '');

-- =====================================================
-- ADD INDEX
-- =====================================================
-- The dynamic table system creates the foreign key and index automatically
-- via the DD trigger when the table_name field is inserted with format='parent'
-- (constraint name: webhook_receivers_table_name_fkey)

-- =====================================================
-- _core/0260_dashboard
-- =====================================================
-- =====================================================
-- DASHBOARD TABLE
-- =====================================================
-- Create table for user-configured dashboards
-- =====================================================

-- =====================================================
-- CREATE dashboards TABLE
-- =====================================================

INSERT INTO entities (
    table_name,
    singular,
    singular_label,
    plural_label,
    description,
    module_id,
    view_permission,
    edit_permission,
    id_column,
    label_column
)
VALUES (
    'dashboards',
    'dashboard',
    'Dashboard',
    'Dashboards',
    'User-configured dashboard layouts and configurations',
    1, -- _core module
    'admin',
    'admin',
    'id',
    'label'
);

-- Add fields to dashboards table
INSERT INTO fields (table_name, field_name, title, format, field_order, input_type, width, description, default_value, reference_table, reference_delete_mode)
VALUES
    ('dashboards', 'config',   'Configuration', 'json',  10, 'default', 'w', 'Dashboard layout and widget configuration', '', '', ''),
    ('dashboards', 'position', 'Position',      'int32', 20, 'default', 'default', 'Display order position', '0', '', '');

INSERT INTO fields (table_name, field_name, title, format, field_order, input_type, width, description, reference_table, reference_delete_mode)
VALUES
    ('dashboards', 'module_id',       'Module',          'reference', 30, 'default', 'default', 'Module this dashboard belongs to',     'modules',     'cascade'),
    ('dashboards', 'view_permission', 'View Permission',  'reference', 40, 'default', 'default', 'Permission required to view this dashboard', 'permissions', 'clear');

-- =====================================================
-- Seed _versions run-once guards (one row per migration)
-- =====================================================
-- So a subsequent `deno task migrate` skips these
-- already-applied migrations instead of re-running them.
INSERT INTO public._versions (name) VALUES
  ('_core.0250_webhook_receiver'),
  ('_core.0260_dashboard')
ON CONFLICT DO NOTHING;

