-- pg_semantius extension upgrade: 0.3.0 -> 0.4.0
-- Generated by `deno task extension` from migrations added since 0.3.0.
-- DO NOT EDIT MANUALLY.

-- =====================================================
-- _versions tracking table (run-once migration guard)
-- =====================================================
-- Created before the migration bodies so _core/0050's
-- `CREATE POLICY ... ON _versions` can attach. The migrate
-- runner creates this via ensureVersionsTable(); CREATE
-- EXTENSION must emit it itself.
CREATE TABLE IF NOT EXISTS _versions (
  name TEXT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_versions_name ON _versions(name);

ALTER TABLE _versions ENABLE ROW LEVEL SECURITY;

-- No new migrations since 0.3.0; version bump only.
