// AUTO-GENERATED by `deno task kyselygen`. Do not edit by hand.

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;
export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;
export type JsonArray = JsonValue[];
export type JsonObject = { [K in string]?: JsonValue };
export type JsonPrimitive = boolean | number | string | null;
export type JsonValue = JsonArray | JsonObject | JsonPrimitive;
export type Json = JsonValue;

export interface AuditDdlLogs {
  id: Generated<Int8>;
  event_time: Timestamp | null;
  user_id: number;
  command_tag: string;
  object_type: string;
  object_identity: string;
  query_text: string;
}

export interface AuditRecordLogs {
  id: Generated<Int8>;
  record_id: string;
  old_record_id: string;
  record_pk: string;
  op: string;
  ts: Timestamp | null;
  user_id: number;
  table_oid: number;
  table_schema: string;
  table_name: string;
  record: Json;
  old_record: Json;
}

export interface Entities {
  table_name: string;
  singular: string;
  plural: string;
  singular_label: string;
  plural_label: string;
  icon_url: string;
  description: string;
  module_id: number | null;
  view_permission: Generated<string>;
  edit_permission: Generated<string>;
  id_column: Generated<string>;
  label_column: Generated<string>;
  managed: Generated<boolean>;
  searchable: boolean;
  is_child: boolean;
  edit_mode: Generated<"auto" | "sidebar" | "modal" | "page" | "">;
  cube_mode: Generated<"disabled" | "auto" | "">;
  audit_log: Generated<boolean>;
  computed_fields: Json;
  validation_rules: Json;
  select_rule: Json;
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface Fields {
  id: string;
  table_name: number;
  field_name: string;
  format: Generated<"json" | "html" | "text" | "multiline" | "code" | "jsonata" | "reference" | "parent" | "enum" | "date" | "time" | "date-time" | "duration" | "uri" | "uri-reference" | "uri-template" | "url" | "email" | "hostname" | "ipv4" | "ipv6" | "regex" | "uuid" | "json-pointer" | "json-pointer-uri-fragment" | "relative-json-pointer" | "byte" | "int32" | "int64" | "float" | "double" | "password" | "binary" | "string" | "number" | "integer" | "boolean" | "object" | "array" | "null">;
  title: string;
  description: string;
  is_pk: boolean;
  default_value: string;
  field_order: number;
  input_type: Generated<"default" | "required" | "readonly" | "disabled" | "hidden">;
  width: Generated<"default" | "s" | "m" | "w">;
  ctype: "" | "id" | "label";
  is_core: boolean;
  searchable: boolean;
  enum_values: Json;
  precision: Generated<number>;
  reference_table: string;
  reference_delete_mode: Generated<"" | "restrict" | "clear" | "cascade">;
  relationship_label: Generated<string>;
  singular_label_parent: string;
  plural_label_parent: string;
  unique_value: boolean;
  cube_type: Generated<"auto" | "dimension" | "measure" | "disabled">;
  input_type_rule: Json;
  updated_at: Generated<Timestamp | null>;
  created_at: Generated<Timestamp | null>;
}

export interface Modules {
  id: Generated<number>;
  module_name: string;
  description: string;
  module_type: "domain" | "master" | "";
  view_permission: string;
  logo_url: string;
  logo_color: string;
  home_page: string;
  module_slug: string;
  manage_permission_id: number | null;
  admin_permission_id: number | null;
  default_viewer_role_id: number | null;
  default_manager_role_id: number | null;
  default_admin_role_id: number | null;
  settings: Json;
  dashboard_config: Json;
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface PermissionHierarchy {
  id: string;
  including_permission_id: number;
  included_permission_id: number;
  origin: "system" | "model" | "model_master" | "user" | "";
  created_at: Generated<Timestamp | null>;
}

export interface Permissions {
  id: Generated<number>;
  permission_name: string;
  description: string;
  module_id: number | null;
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface ProcessGates {
  id: Generated<number>;
  name: string;
  process_id: number;
  entity: string;
  gate_kind: "approval" | "submit_lock" | "ownership" | "create" | "transition";
  to_state: string;
  state_column: Generated<string>;
  emits_events: boolean;
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface Processes {
  id: Generated<number>;
  name: string;
  module_id: number | null;
  process_key: string;
  description: string;
  ordering: number;
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface QueueTableEvents {
  event_name: string;
  id: Generated<number>;
  queue_id: number;
  table_name: number | null;
  event_handler: "insert" | "update" | "upsert" | "delete" | "change";
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface Queues {
  id: Generated<number>;
  queue_name: string;
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface RaciAssignments {
  id: Generated<number>;
  name: string;
  process_id: number;
  role_id: number | null;
  raci: "responsible" | "accountable" | "consulted" | "informed";
  consult_mode: Generated<"read" | "notify" | "block" | "">;
  origin: Generated<"system" | "user" | "">;
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface RaciEvents {
  id: Generated<number>;
  process_id: number;
  entity: string;
  record_id: string;
  raci: "consulted" | "informed";
  target_role_id: number | null;
  status: Generated<"pending" | "sent" | "acted">;
  acted_at: Timestamp | null;
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface RolePermissions {
  id: string;
  role_id: number;
  permission_id: number;
  granted_at: Timestamp | null;
  granted_by: number | null;
}

export interface Roles {
  id: Generated<number>;
  role_name: string;
  slug: string;
  description: string;
  origin: "system" | "model" | "model_master" | "user" | "";
  module_id: number | null;
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface UserPermissions {
  id: string;
  user_id: number;
  permission_id: number;
  granted_at: Timestamp | null;
  granted_by: number | null;
}

export interface UserRoles {
  id: string;
  user_id: number;
  role_id: number;
  assigned_at: Timestamp | null;
  assigned_by: number | null;
}

export interface Users {
  id: Generated<number>;
  external_id: string;
  email: string;
  first_name: string;
  last_name: string;
  display_name: string;
  is_disabled: boolean;
  settings: Json;
  created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
  last_seen: Timestamp | null;
  is_agent: Generated<boolean>;
}

export interface DB {
  audit_ddl_logs: AuditDdlLogs;
  audit_record_logs: AuditRecordLogs;
  entities: Entities;
  fields: Fields;
  modules: Modules;
  permission_hierarchy: PermissionHierarchy;
  permissions: Permissions;
  process_gates: ProcessGates;
  processes: Processes;
  queue_table_events: QueueTableEvents;
  queues: Queues;
  raci_assignments: RaciAssignments;
  raci_events: RaciEvents;
  role_permissions: RolePermissions;
  roles: Roles;
  user_permissions: UserPermissions;
  user_roles: UserRoles;
  users: Users;
}
