-- =====================================================
-- DYNAMIC TABLE MANAGEMENT SCHEMA - triggers and grants
-- =====================================================
-- Repeatable. The tables are in 0130_dd_schema.once.sql.

-- Create trigger function to validate reference_table when not empty
-- We use a trigger instead of CHECK constraint to allow subqueries
CREATE OR REPLACE FUNCTION validate_reference_table()
RETURNS TRIGGER AS $$
BEGIN
    -- Only validate if reference_table is not empty
    IF NEW.reference_table != '' THEN
        -- Check if the referenced table exists
        IF NOT EXISTS (SELECT 1 FROM entities WHERE table_name = NEW.reference_table) THEN
            RAISE EXCEPTION 'Referenced table ${table} not found in entities'
                USING ERRCODE = '90212',
                      HINT = jsonb_build_object('table', NEW.reference_table)::text;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

COMMENT ON FUNCTION validate_reference_table IS
'Trigger function that rejects a field whose reference_table is set but does not match any entities.table_name. Enforced via trigger (not a CHECK) so it can run a subquery.';

CREATE OR REPLACE TRIGGER validate_reference_table_trigger
    BEFORE INSERT OR UPDATE ON fields
    FOR EACH ROW
    EXECUTE FUNCTION validate_reference_table();

-- The four policies of each table are generated by create_entity_policies()
-- in 0240_dd_bootstrap_complete.once.sql, from the entities rows registered in
-- 0150_dd_bootstrap.once.sql, like those of every other entity; see the note in
-- 0100_rbac_rls.sql.

-- =====================================================
-- GRANT THE REQUEST ROLE ACCESS TO THE METADATA TABLES
-- =====================================================
-- These two are created after the one-time GRANT ... ON ALL TABLES in
-- 0110_rbac_grants.once.sql and there is no default privilege in this schema to
-- pick them up, so the request role reaches them only through this grant. It
-- comes after the RLS enable (0130_dd_schema.once.sql): a grant is what
-- publishes a table through the Data API, and with RLS on and no policy yet the
-- table stays closed to the request role until
-- 0240_dd_bootstrap_complete.once.sql generates its policies. Neither table has
-- a sequence - entities is keyed by table_name and fields.id is a generated
-- text column.
GRANT SELECT, INSERT, UPDATE, DELETE ON entities, fields TO semantius_user;

-- =====================================================
-- AUTO-SET PLURAL TRIGGER
-- =====================================================
-- Automatically sets plural to match table_name on INSERT/UPDATE
-- This ensures plural always equals table_name and ignores user input

CREATE OR REPLACE FUNCTION auto_set_plural()
RETURNS TRIGGER AS $$
BEGIN
    -- Always set plural to table_name, ignoring any provided value
    NEW.plural := NEW.table_name;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

COMMENT ON FUNCTION auto_set_plural IS 
'Trigger function that automatically sets plural column to match table_name, ignoring user input';

CREATE OR REPLACE TRIGGER auto_set_plural_trigger
    BEFORE INSERT OR UPDATE ON entities
    FOR EACH ROW
    EXECUTE FUNCTION auto_set_plural();

COMMENT ON TRIGGER auto_set_plural_trigger ON entities IS
'Automatically sets plural to match table_name on INSERT/UPDATE';

-- =====================================================
-- UPDATE TIMESTAMP TRIGGERS
-- =====================================================
-- Uses common.update_updated_at_column() from common schema

CREATE OR REPLACE TRIGGER update_entities_updated_at
    BEFORE UPDATE ON entities
    FOR EACH ROW
    EXECUTE FUNCTION common.update_updated_at_column();

CREATE OR REPLACE TRIGGER update_fields_updated_at
    BEFORE UPDATE ON fields
    FOR EACH ROW
    EXECUTE FUNCTION common.update_updated_at_column();

-- =====================================================
-- PROVENANCE: catalog_entity_aliases append-only guard (v0.1.2)
-- =====================================================
-- A cross-domain reuse/merge APPENDS an alias element ({alias_code, source_domain, ...});
-- prior elements are never removed or rewritten. Enforced as a narrow BEFORE UPDATE guard
-- (cheaper + more targeted than a JsonLogic validation rule, and avoids running the full
-- compute_validate machinery for this one check): the new array must contain every element
-- of the old one (jsonb @> superset). The WHEN clause skips the no-op common case, so it is
-- inert during renames and metadata edits. Rejection shares the 23514 class used by
-- validation_rules. SECURITY DEFINER + pinned search_path per house style.

CREATE OR REPLACE FUNCTION enforce_catalog_aliases_append_only()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT (NEW.catalog_entity_aliases @> OLD.catalog_entity_aliases) THEN
        RAISE EXCEPTION 'catalog_entity_aliases is append-only: existing alias elements cannot be removed or rewritten'
            USING ERRCODE = '90213';
    END IF;
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION enforce_catalog_aliases_append_only IS
'BEFORE UPDATE guard on entities: catalog_entity_aliases may only grow (new array must contain all prior elements via jsonb @>). Enforces the append-only cross-domain merge ledger.';

REVOKE EXECUTE ON FUNCTION enforce_catalog_aliases_append_only() FROM PUBLIC;

CREATE OR REPLACE TRIGGER enforce_catalog_aliases_append_only_trigger
    BEFORE UPDATE ON entities
    FOR EACH ROW
    WHEN (OLD.catalog_entity_aliases IS DISTINCT FROM NEW.catalog_entity_aliases)
    EXECUTE FUNCTION enforce_catalog_aliases_append_only();

-- Revoke default PUBLIC execute on trigger functions defined in this file
REVOKE EXECUTE ON FUNCTION validate_reference_table() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION auto_set_plural() FROM PUBLIC;
