// AUTO-GENERATED by `deno task drizzlegen`. Do not edit by hand.

import { boolean, date, integer, numeric, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  categoryName: text("category_name").notNull(),
  description: text("description").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const customers = pgTable("customers", {
  id: serial("id").primaryKey(),
  companyName: text("company_name").notNull(),
  customerId: text("customer_id").notNull(),
  contactName: text("contact_name").notNull(),
  contactTitle: text("contact_title").notNull(),
  address: text("address").notNull(),
  city: text("city").notNull(),
  region: text("region").notNull(),
  postalCode: text("postal_code").notNull(),
  country: text("country").notNull(),
  phone: text("phone").notNull(),
  fax: text("fax").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const employeeTerritories = pgTable("employee_territories", {
  id: serial("id").primaryKey(),
  employeeId: integer("employee_id").references((): AnyPgColumn => employees.id, { onDelete: "cascade" }).notNull(),
  territoryId: integer("territory_id").references((): AnyPgColumn => territories.id, { onDelete: "cascade" }).notNull(),
  label: text("label").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const employees = pgTable("employees", {
  id: serial("id").primaryKey(),
  lastName: text("last_name").notNull(),
  firstName: text("first_name").notNull(),
  title: text("title").notNull(),
  titleOfCourtesy: text("title_of_courtesy", { enum: ["Mr.", "Mrs.", "Ms.", "Dr.", ""] }).notNull(),
  birthDate: date("birth_date"),
  hireDate: date("hire_date"),
  address: text("address").notNull(),
  city: text("city").notNull(),
  region: text("region").notNull(),
  postalCode: text("postal_code").notNull(),
  country: text("country").notNull(),
  homePhone: text("home_phone").notNull(),
  extension: text("extension").notNull(),
  notes: text("notes").notNull(),
  photoPath: text("photo_path").notNull(),
  reportsTo: integer("reports_to").references((): AnyPgColumn => employees.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const orderDetails = pgTable("order_details", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").references((): AnyPgColumn => orders.id, { onDelete: "cascade" }).notNull(),
  productId: integer("product_id").references((): AnyPgColumn => products.id, { onDelete: "cascade" }).notNull(),
  label: text("label").notNull(),
  unitPrice: numeric("unit_price", { precision: 18, scale: 2 }).notNull().default("0.0"),
  quantity: integer("quantity").notNull().default(0),
  discount: numeric("discount", { precision: 18, scale: 2 }).notNull().default("0.0"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const orders = pgTable("orders", {
  id: serial("id").primaryKey(),
  shipName: text("ship_name").notNull(),
  status: text("status", { enum: ["pending", "shipped"] }).notNull().default("pending"),
  customerId: integer("customer_id").references((): AnyPgColumn => customers.id),
  employeeId: integer("employee_id").references((): AnyPgColumn => employees.id),
  shipVia: integer("ship_via").references((): AnyPgColumn => shippers.id),
  shipAddress: text("ship_address").notNull(),
  shipCity: text("ship_city").notNull(),
  shipRegion: text("ship_region").notNull(),
  shipPostalCode: text("ship_postal_code").notNull(),
  shipCountry: text("ship_country").notNull(),
  freight: numeric("freight", { precision: 18, scale: 2 }).notNull().default("0.0"),
  orderDate: date("order_date"),
  requiredDate: date("required_date"),
  shippedDate: date("shipped_date"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const products = pgTable("products", {
  id: serial("id").primaryKey(),
  productName: text("product_name").notNull(),
  categoryId: integer("category_id").references((): AnyPgColumn => categories.id),
  supplierId: integer("supplier_id").references((): AnyPgColumn => suppliers.id),
  quantityPerUnit: text("quantity_per_unit").notNull(),
  unitPrice: numeric("unit_price", { precision: 18, scale: 2 }).notNull().default("0.0"),
  unitsInStock: integer("units_in_stock").notNull().default(0),
  unitsOnOrder: integer("units_on_order").notNull().default(0),
  reorderLevel: integer("reorder_level").notNull().default(0),
  discontinued: boolean("discontinued").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const regions = pgTable("regions", {
  id: serial("id").primaryKey(),
  regionDescription: text("region_description").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const shippers = pgTable("shippers", {
  id: serial("id").primaryKey(),
  companyName: text("company_name").notNull(),
  phone: text("phone").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const suppliers = pgTable("suppliers", {
  id: serial("id").primaryKey(),
  contactName: text("contact_name").notNull(),
  companyName: text("company_name").notNull(),
  contactTitle: text("contact_title").notNull(),
  address: text("address").notNull(),
  city: text("city").notNull(),
  region: text("region").notNull(),
  postalCode: text("postal_code").notNull(),
  country: text("country").notNull(),
  phone: text("phone").notNull(),
  fax: text("fax").notNull(),
  homepage: text("homepage").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const territories = pgTable("territories", {
  territoryId: text("territory_id").notNull(),
  id: serial("id").primaryKey(),
  territoryDescription: text("territory_description").notNull(),
  regionId: integer("region_id").references((): AnyPgColumn => regions.id),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const categoriesRelations = relations(categories, ({ many }) => ({
  products: many(products, { relationName: "products_category_id" }),
}));

export const customersRelations = relations(customers, ({ many }) => ({
  orders: many(orders, { relationName: "orders_customer_id" }),
}));

export const employeeTerritoriesRelations = relations(employeeTerritories, ({ one }) => ({
  employee: one(employees, { fields: [employeeTerritories.employeeId], references: [employees.id], relationName: "employee_territories_employee_id" }),
  territory: one(territories, { fields: [employeeTerritories.territoryId], references: [territories.id], relationName: "employee_territories_territory_id" }),
}));

export const employeesRelations = relations(employees, ({ one, many }) => ({
  reportsTo: one(employees, { fields: [employees.reportsTo], references: [employees.id], relationName: "employees_reports_to" }),
  employees: many(employees, { relationName: "employees_reports_to" }),
  employeeTerritories: many(employeeTerritories, { relationName: "employee_territories_employee_id" }),
  orders: many(orders, { relationName: "orders_employee_id" }),
}));

export const orderDetailsRelations = relations(orderDetails, ({ one }) => ({
  order: one(orders, { fields: [orderDetails.orderId], references: [orders.id], relationName: "order_details_order_id" }),
  product: one(products, { fields: [orderDetails.productId], references: [products.id], relationName: "order_details_product_id" }),
}));

export const ordersRelations = relations(orders, ({ one, many }) => ({
  customer: one(customers, { fields: [orders.customerId], references: [customers.id], relationName: "orders_customer_id" }),
  employee: one(employees, { fields: [orders.employeeId], references: [employees.id], relationName: "orders_employee_id" }),
  shipVia: one(shippers, { fields: [orders.shipVia], references: [shippers.id], relationName: "orders_ship_via" }),
  orderDetails: many(orderDetails, { relationName: "order_details_order_id" }),
}));

export const productsRelations = relations(products, ({ one, many }) => ({
  category: one(categories, { fields: [products.categoryId], references: [categories.id], relationName: "products_category_id" }),
  supplier: one(suppliers, { fields: [products.supplierId], references: [suppliers.id], relationName: "products_supplier_id" }),
  orderDetails: many(orderDetails, { relationName: "order_details_product_id" }),
}));

export const regionsRelations = relations(regions, ({ many }) => ({
  territories: many(territories, { relationName: "territories_region_id" }),
}));

export const shippersRelations = relations(shippers, ({ many }) => ({
  orders: many(orders, { relationName: "orders_ship_via" }),
}));

export const suppliersRelations = relations(suppliers, ({ many }) => ({
  products: many(products, { relationName: "products_supplier_id" }),
}));

export const territoriesRelations = relations(territories, ({ one, many }) => ({
  region: one(regions, { fields: [territories.regionId], references: [regions.id], relationName: "territories_region_id" }),
  employeeTerritories: many(employeeTerritories, { relationName: "employee_territories_territory_id" }),
}));
