/**
 * Coverage collection for `deno task test --coverage`.
 *
 * Measures which parts of Semantius core (the pg_semantius extension, or the
 * migrate-installed equivalent) the pgTAP suite actually executes:
 *
 *   - function level, every language: `SET track_functions = 'all'` and
 *     before/after deltas of pg_stat_user_functions on the runner's connection
 *   - statement level for PL/pgSQL: the plpgsql_check profiler, session-local
 *     on the single test connection (no shared_preload_libraries needed)
 *   - table level: pg_stat_user_tables deltas
 *
 * Everything degrades gracefully: without plpgsql_check only function-level
 * data is produced; without superuser (no SET track_functions) SQL-language
 * functions are reported as "not measurable". Reports are written to
 * <outDir>/summary.json, uncovered.md and lcov.info. Nothing here calls
 * Deno.exit: the test command decides the exit code after the reports exist.
 *
 * Two plpgsql_check quirks this module works around:
 *   - plpgsql_coverage_statements() returns 1.0 for a function that was never
 *     executed, so "called" is decided from call/exec counts first;
 *   - the profile is keyed per function oid, so the per-test functions the
 *     data dictionary generates and rolls back are simply not in the universe.
 */

import type { Client } from "@postgres";

export interface CoverageOptions {
  enabled: boolean;
  /** Minimum function coverage in percent; undefined = no gate. */
  min?: number;
  outDir: string;
  /** Prefix console lines with "# " so plain TAP output stays parseable. */
  tap?: boolean;
}

export interface CoverageCapabilities {
  serverVersion: string;
  user: string;
  superuser: boolean;
  plpgsqlCheck: {
    available: boolean;
    schema?: string;
    version?: string;
    reason?: string;
  };
  trackFunctions: { enabled: boolean; reason?: string };
  universe: {
    mode: "extension" | "schemas";
    extension?: string;
    schemas?: string[];
  };
}

export interface FunctionCoverage {
  oid: number;
  schema: string;
  name: string;
  /** pg_get_function_identity_arguments() */
  args: string;
  language: string;
  kind: "function" | "procedure" | "trigger";
  securityDefiner: boolean;
  /** Runtime-generated by the data dictionary (_label, <fk>_label, compute_validate_*, select_rule_*). */
  generated: boolean;
  /** Delta of pg_stat_user_functions.calls; null when track_functions is unavailable. */
  calls: number | null;
  /** plpgsql_check profiler exec_count; null when the profiler is unavailable or the function is not PL/pgSQL. */
  execCount: number | null;
  /** true/false when measurable, null when neither counter can see this function. */
  called: boolean | null;
  statements: { total: number; executed: number; pct: number } | null;
  branchesPct: number | null;
  /** Where the live definition lives (last definition in migrate order wins). */
  source: { file: string; headerLine: number; bodyLine: number } | null;
  /** [fileLine, hits] per profiled statement, only when source is mapped. */
  lineHits: [number, number][] | null;
  /** File line numbers of statements that never executed. */
  uncoveredLines: number[];
  lineDetailError?: string;
}

export interface TableCoverage {
  oid: number;
  schema: string;
  name: string;
  policies: number;
  touched: boolean;
  seqScan: number;
  idxScan: number;
  inserts: number;
  updates: number;
  deletes: number;
}

export interface CoverageSummary {
  version: 1;
  generatedAt: string;
  database: string;
  capabilities: CoverageCapabilities;
  run: {
    filter?: string;
    failFast: boolean;
    stoppedEarly: boolean;
    files: number;
    testsPassed: boolean;
    partial: boolean;
  };
  totals: {
    functions: {
      total: number;
      measurable: number;
      called: number;
      pct: number | null;
      neverCalled: number;
      unmeasurable: number;
      generated: number;
    };
    statements: { total: number; executed: number; pct: number } | null;
    tables: { total: number; touched: number; pct: number | null };
  };
  threshold: { min?: number; metric: "functions"; passed: boolean | null };
  functions: FunctionCoverage[];
  tables: TableCoverage[];
}

interface TableStats {
  seq: number;
  idx: number;
  ins: number;
  upd: number;
  del: number;
}

interface StatsSnapshot {
  functions: Map<number, number>;
  tables: Map<number, TableStats>;
}

interface UniverseFunction {
  oid: number;
  schema: string;
  name: string;
  args: string;
  language: string;
  prokind: string;
  prosecdef: boolean;
  isTrigger: boolean;
  prosrc: string;
}

interface UniverseTable {
  oid: number;
  schema: string;
  name: string;
  policies: number;
}

const CORE_SCHEMAS = ["public", "common", "rbac", "audit", "pgmq"];
const TEST_HELPERS = ["authenticate_as", "extract_api_key_id"];

/** Decode deno-postgres numerics (int8 arrives as bigint, float8 as number). */
function num(v: unknown): number {
  if (typeof v === "bigint") return Number(v);
  if (typeof v === "number") return v;
  if (typeof v === "string") return Number(v);
  return 0;
}

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function maskUrl(url: string): string {
  return url.replace(/\/\/[^@]+@/, "//***:***@");
}

function pct(part: number, whole: number): number | null {
  return whole > 0 ? (part / whole) * 100 : null;
}

function fmtPct(value: number | null): string {
  return value === null ? "n/a" : `${value.toFixed(1)}%`;
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/** Compress sorted line numbers into "12-15, 20, 31-33". */
function compressRanges(lines: number[]): string {
  if (lines.length === 0) return "";
  const parts: string[] = [];
  let start = lines[0];
  let prev = lines[0];
  for (let i = 1; i <= lines.length; i++) {
    const cur = lines[i];
    if (cur === prev + 1) {
      prev = cur;
      continue;
    }
    parts.push(start === prev ? `${start}` : `${start}-${prev}`);
    start = cur;
    prev = cur;
  }
  return parts.join(", ");
}

function chunks<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) {
    out.push(items.slice(i, i + size));
  }
  return out;
}

// ---------------------------------------------------------------------------
// Source mapping: pg_proc.prosrc -> apps/<app>/migrations/<file>.sql:<line>
// ---------------------------------------------------------------------------

interface SourceHeader {
  index: number;
  line: number;
  schema?: string;
  name: string;
}

interface SourceFile {
  path: string;
  text: string;
  lineStarts: number[];
  headers: SourceHeader[];
}

interface SourceLocation {
  file: string;
  headerLine: number;
  bodyLine: number;
}

/** 1-based line number of a character offset. */
function lineAt(lineStarts: number[], index: number): number {
  let lo = 0;
  let hi = lineStarts.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (lineStarts[mid] <= index) lo = mid;
    else hi = mid - 1;
  }
  return lo + 1;
}

/**
 * Loads every migration file in migrate order (apps/_core first, then the other
 * apps sorted by name; apps/test is skipped because it only holds pgtap). The
 * function bodies are stored verbatim by both install channels (migrate sends
 * the file as-is, the extension generator only rewrites CREATE EXTENSION lines),
 * so prosrc is byte-identical to the dollar-quoted text in the file.
 */
async function buildSourceIndex(): Promise<SourceFile[]> {
  const apps: string[] = [];
  try {
    for await (const entry of Deno.readDir("./apps")) {
      if (
        entry.isDirectory && entry.name !== "_core" && entry.name !== "test"
      ) {
        apps.push(entry.name);
      }
    }
  } catch {
    return [];
  }
  apps.sort();

  const files: SourceFile[] = [];
  for (const app of ["_core", ...apps]) {
    const dir = `./apps/${app}/migrations`;
    const names: string[] = [];
    try {
      for await (const entry of Deno.readDir(dir)) {
        if (entry.isFile && entry.name.endsWith(".sql")) names.push(entry.name);
      }
    } catch {
      continue;
    }
    names.sort();
    for (const name of names) {
      const raw = await Deno.readTextFile(`${dir}/${name}`);
      const text = raw.replace(/\r\n?/g, "\n");
      const lineStarts = [0];
      for (let i = 0; i < text.length; i++) {
        if (text.charCodeAt(i) === 10) lineStarts.push(i + 1);
      }
      const headers: SourceHeader[] = [];
      const re =
        /CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+(?:"?([A-Za-z_][A-Za-z0-9_]*)"?\.)?"?([A-Za-z_][A-Za-z0-9_]*)"?/gi;
      let m: RegExpExecArray | null;
      while ((m = re.exec(text)) !== null) {
        headers.push({
          index: m.index,
          line: lineAt(lineStarts, m.index),
          schema: m[1]?.toLowerCase(),
          name: m[2].toLowerCase(),
        });
      }
      files.push({
        path: `apps/${app}/migrations/${name}`,
        text,
        lineStarts,
        headers,
      });
    }
  }
  return files;
}

/**
 * Finds the migration line where a function body is defined. The body text
 * alone is ambiguous (dozens of trigger functions share "BEGIN RETURN NEW; END"),
 * so a match only counts when the nearest preceding CREATE FUNCTION header
 * names the same function. The last match in migrate order wins, which is the
 * definition that is live in the database.
 */
function locateFunction(
  index: SourceFile[],
  fn: { schema: string; name: string; prosrc: string },
): SourceLocation | null {
  const body = fn.prosrc.replace(/\r\n?/g, "\n");
  if (body.trim() === "") return null;
  const name = fn.name.toLowerCase();
  const schema = fn.schema.toLowerCase();
  let best: SourceLocation | null = null;

  for (const file of index) {
    let from = 0;
    let i: number;
    while ((i = file.text.indexOf(body, from)) !== -1) {
      from = i + 1;
      let header: SourceHeader | undefined;
      for (const h of file.headers) {
        if (h.index < i) header = h;
        else break;
      }
      if (!header || header.name !== name) continue;
      if (header.schema && header.schema !== schema) continue;
      best = {
        file: file.path,
        headerLine: header.line,
        bodyLine: lineAt(file.lineStarts, i),
      };
    }
  }
  return best;
}

// ---------------------------------------------------------------------------
// Collector
// ---------------------------------------------------------------------------

export class CoverageCollector {
  private client: Client;
  private opts: CoverageOptions;
  private before: StatsSnapshot = { functions: new Map(), tables: new Map() };
  caps: CoverageCapabilities = {
    serverVersion: "",
    user: "",
    superuser: false,
    plpgsqlCheck: { available: false },
    trackFunctions: { enabled: false },
    universe: { mode: "schemas", schemas: CORE_SCHEMAS },
  };

  constructor(client: Client, opts: CoverageOptions) {
    this.client = client;
    this.opts = opts;
  }

  private log(line: string): void {
    console.log(this.opts.tap ? `# ${line}` : line);
  }

  private warn(line: string): void {
    console.warn(this.opts.tap ? `# ${line}` : line);
  }

  private async rows<T>(sql: string): Promise<T[]> {
    const result = await this.client.queryObject<T>(sql);
    return result.rows;
  }

  private get ext(): string {
    return quoteIdent(this.caps.plpgsqlCheck.schema ?? "extensions");
  }

  /**
   * Prepares the session. Every step is its own statement so that a failure
   * (no extension, no superuser) degrades that one capability instead of the
   * whole run. Runs once, before the first test file, on the test connection.
   */
  async preflight(): Promise<CoverageCapabilities> {
    const [id] = await this.rows<
      { version: string; user: string; superuser: boolean }
    >(
      `SELECT pg_catalog.version() AS version, current_user::text AS "user",
              pg_catalog.current_setting('is_superuser') = 'on' AS superuser`,
    );
    this.caps.serverVersion = id.version;
    this.caps.user = id.user;
    this.caps.superuser = id.superuser;

    // plpgsql_check: available? install into `extensions` (skipped by dropall
    // and by the 0240 guard test), then resolve where it actually lives.
    const avail = await this.rows<
      { installed_version: string | null; default_version: string }
    >(
      `SELECT installed_version, default_version
         FROM pg_catalog.pg_available_extensions WHERE name = 'plpgsql_check'`,
    );
    if (avail.length === 0) {
      this.caps.plpgsqlCheck = {
        available: false,
        reason:
          "plpgsql_check is not available on this server (statement coverage disabled)",
      };
    } else {
      try {
        if (!avail[0].installed_version) {
          await this.client.queryArray(
            `CREATE SCHEMA IF NOT EXISTS extensions`,
          );
          await this.client.queryArray(
            `CREATE EXTENSION IF NOT EXISTS plpgsql_check WITH SCHEMA extensions`,
          );
        }
        const [ext] = await this.rows<{ schema: string; version: string }>(
          `SELECT n.nspname AS schema, e.extversion AS version
             FROM pg_catalog.pg_extension e
             JOIN pg_catalog.pg_namespace n ON n.oid = e.extnamespace
            WHERE e.extname = 'plpgsql_check'`,
        );
        this.caps.plpgsqlCheck = {
          available: true,
          schema: ext.schema,
          version: ext.version,
        };
        if (ext.schema !== "extensions") {
          this.warn(
            `plpgsql_check is installed in schema "${ext.schema}"; deno task dropall only skips the "extensions" schema`,
          );
        }
        // Calling into the extension loads its library into this session and
        // installs the PL/pgSQL plugin hooks; also proves EXECUTE privilege.
        await this.client.queryArray(
          `SELECT ${this.ext}.plpgsql_profiler_reset_all()`,
        );
        await this.client.queryArray(`SET plpgsql_check.profiler = on`);
        await this.client.queryArray(`SET plpgsql_check.use_lxcache = off`);
      } catch (error) {
        this.caps.plpgsqlCheck = {
          available: false,
          reason: `plpgsql_check could not be enabled: ${errorMessage(error)}`,
        };
      }
    }

    // Function call counters for every language (superuser-only GUC).
    try {
      await this.client.queryArray(`SET track_functions = 'all'`);
      this.caps.trackFunctions = { enabled: true };
    } catch (error) {
      this.caps.trackFunctions = {
        enabled: false,
        reason: `cannot SET track_functions (${
          errorMessage(error)
        }); SQL-language functions are not measurable`,
      };
    }

    // Always the schema universe. It used to switch to extension membership
    // when pg_semantius was installed, but the extension is now a THIN
    // INSTALLER: its only members are the `semantius` schema and a handful of
    // installer functions, so the membership universe would report ~4 objects
    // and miss every core function the suite actually exercises. Both install
    // layouts produce the same ordinary objects in the same five schemas.
    this.caps.universe = { mode: "schemas", schemas: CORE_SCHEMAS };

    const parts: string[] = [];
    parts.push(
      this.caps.plpgsqlCheck.available
        ? `plpgsql_check ${this.caps.plpgsqlCheck.version} (schema ${this.caps.plpgsqlCheck.schema})`
        : "plpgsql_check unavailable",
    );
    parts.push(
      this.caps.trackFunctions.enabled
        ? "track_functions on"
        : "track_functions off",
    );
    parts.push(
      this.caps.universe.mode === "extension"
        ? "universe: extension pg_semantius"
        : `universe: schemas ${CORE_SCHEMAS.join(",")}`,
    );
    this.log(`Coverage: ${parts.join("; ")}`);
    if (!this.caps.plpgsqlCheck.available && this.caps.plpgsqlCheck.reason) {
      this.warn(`Coverage: ${this.caps.plpgsqlCheck.reason}`);
    }
    if (!this.caps.trackFunctions.enabled && this.caps.trackFunctions.reason) {
      this.warn(`Coverage: ${this.caps.trackFunctions.reason}`);
    }
    if (
      !this.caps.plpgsqlCheck.available && !this.caps.trackFunctions.enabled
    ) {
      this.warn(
        "Coverage: neither the profiler nor function statistics are available; nothing can be measured on this connection",
      );
    }
    return this.caps;
  }

  private async snapshot(): Promise<StatsSnapshot> {
    const functions = new Map<number, number>();
    for (
      const r of await this.rows<{ oid: unknown; calls: unknown }>(
        `SELECT funcid::bigint AS oid, calls::bigint AS calls
           FROM pg_catalog.pg_stat_user_functions`,
      )
    ) {
      functions.set(num(r.oid), num(r.calls));
    }
    const tables = new Map<number, TableStats>();
    for (
      const r of await this.rows<
        {
          oid: unknown;
          seq: unknown;
          idx: unknown;
          ins: unknown;
          upd: unknown;
          del: unknown;
        }
      >(
        `SELECT relid::bigint AS oid,
                COALESCE(seq_scan, 0)::bigint AS seq, COALESCE(idx_scan, 0)::bigint AS idx,
                COALESCE(n_tup_ins, 0)::bigint AS ins, COALESCE(n_tup_upd, 0)::bigint AS upd,
                COALESCE(n_tup_del, 0)::bigint AS del
           FROM pg_catalog.pg_stat_user_tables`,
      )
    ) {
      tables.set(num(r.oid), {
        seq: num(r.seq),
        idx: num(r.idx),
        ins: num(r.ins),
        upd: num(r.upd),
        del: num(r.del),
      });
    }
    return { functions, tables };
  }

  /** Records the counters before the first test file runs. */
  async snapshotBefore(): Promise<void> {
    this.before = await this.snapshot();
  }

  private universeFunctionsSql(): string {
    const base = `
      SELECT p.oid::bigint AS oid, n.nspname AS schema, p.proname AS name,
             pg_catalog.pg_get_function_identity_arguments(p.oid) AS args,
             l.lanname AS language, p.prokind::text AS prokind, p.prosecdef,
             (p.prorettype IN ('pg_catalog.trigger'::pg_catalog.regtype,
                               'pg_catalog.event_trigger'::pg_catalog.regtype)) AS is_trigger,
             p.prosrc
        FROM pg_catalog.pg_proc p
        JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
        JOIN pg_catalog.pg_language l ON l.oid = p.prolang
       WHERE l.lanname IN ('plpgsql', 'sql')`;
    const generated = `(n.nspname = 'public' AND (
             p.proname = '_label'
          OR (p.proname LIKE '%\\_label' AND pg_catalog.pg_get_function_identity_arguments(p.oid) LIKE 'rec %')
          OR p.proname LIKE 'compute\\_validate\\_%'
          OR p.proname LIKE 'select\\_rule\\_%'))`;
    const anyExtensionMember = `EXISTS (
          SELECT 1 FROM pg_catalog.pg_depend d
           WHERE d.classid = 'pg_catalog.pg_proc'::pg_catalog.regclass AND d.objid = p.oid
             AND d.deptype = 'e')`;
    if (this.caps.universe.mode === "extension") {
      const member = `EXISTS (
          SELECT 1 FROM pg_catalog.pg_depend d
            JOIN pg_catalog.pg_extension e ON e.oid = d.refobjid
           WHERE d.classid = 'pg_catalog.pg_proc'::pg_catalog.regclass AND d.objid = p.oid
             AND d.refclassid = 'pg_catalog.pg_extension'::pg_catalog.regclass
             AND d.deptype = 'e' AND e.extname = '${this.caps.universe.extension}')`;
      return `${base}
         AND (${member}
              OR (${generated} AND NOT ${anyExtensionMember}))
       ORDER BY 2, 3, 4`;
    }
    const schemas = CORE_SCHEMAS.map((s) => `'${s}'`).join(", ");
    const helpers = TEST_HELPERS.map((s) => `'${s}'`).join(", ");
    return `${base}
         AND n.nspname IN (${schemas})
         AND p.proname NOT IN (${helpers})
         AND NOT ${anyExtensionMember}
       ORDER BY 2, 3, 4`;
  }

  private universeTablesSql(): string {
    const base = `
      SELECT c.oid::bigint AS oid, n.nspname AS schema, c.relname AS name,
             (SELECT count(*) FROM pg_catalog.pg_policy pol WHERE pol.polrelid = c.oid)::bigint AS policies
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
       WHERE c.relkind IN ('r', 'p')`;
    if (this.caps.universe.mode === "extension") {
      return `${base}
         AND EXISTS (
          SELECT 1 FROM pg_catalog.pg_depend d
            JOIN pg_catalog.pg_extension e ON e.oid = d.refobjid
           WHERE d.classid = 'pg_catalog.pg_class'::pg_catalog.regclass AND d.objid = c.oid
             AND d.refclassid = 'pg_catalog.pg_extension'::pg_catalog.regclass
             AND d.deptype = 'e' AND e.extname = '${this.caps.universe.extension}')
       ORDER BY 2, 3`;
    }
    const schemas = CORE_SCHEMAS.map((s) => `'${s}'`).join(", ");
    return `${base}
         AND n.nspname IN (${schemas})
         AND NOT EXISTS (
          SELECT 1 FROM pg_catalog.pg_depend d
           WHERE d.classid = 'pg_catalog.pg_class'::pg_catalog.regclass AND d.objid = c.oid
             AND d.deptype = 'e')
       ORDER BY 2, 3`;
  }

  /**
   * Reads the counters and the profiler after the suite ran and turns them
   * into a summary. Must run on the same connection as the tests (the
   * profiler data is session-local unless plpgsql_check is preloaded).
   */
  async collect(
    run: CoverageSummary["run"],
    databaseUrl: string,
  ): Promise<CoverageSummary> {
    // Tests SET ROLE inside their rolled-back transactions; be defensive anyway.
    try {
      await this.client.queryArray(`RESET ROLE`);
    } catch {
      // ignore
    }
    // Counters are flushed to shared memory when the backend goes idle; force
    // the next flush and give it one more round trip so the after-snapshot
    // includes the last test file.
    try {
      await this.client.queryArray(
        `SELECT pg_catalog.pg_stat_force_next_flush()`,
      );
      await this.client.queryArray(`SELECT 1`);
    } catch {
      // pre-15 servers: the 1s flush interval usually has passed anyway
    }
    const after = await this.snapshot();

    const universe = (await this.rows<
      {
        oid: unknown;
        schema: string;
        name: string;
        args: string;
        language: string;
        prokind: string;
        prosecdef: boolean;
        is_trigger: boolean;
        prosrc: string;
      }
    >(this.universeFunctionsSql())).map((r): UniverseFunction => ({
      oid: num(r.oid),
      schema: r.schema,
      name: r.name,
      args: r.args,
      language: r.language,
      prokind: r.prokind,
      prosecdef: r.prosecdef,
      isTrigger: r.is_trigger,
      prosrc: r.prosrc,
    }));
    const tables = (await this.rows<
      { oid: unknown; schema: string; name: string; policies: unknown }
    >(this.universeTablesSql())).map((r): UniverseTable => ({
      oid: num(r.oid),
      schema: r.schema,
      name: r.name,
      policies: num(r.policies),
    }));

    const callsOf = (oid: number) =>
      (after.functions.get(oid) ?? 0) - (this.before.functions.get(oid) ?? 0);

    // Profiler data (session-local): exec counts, branch ratios, statements.
    const execCounts = new Map<number, number>();
    const branches = new Map<number, number>();
    const statements = new Map<number, { lineno: number; exec: number }[]>();
    const lineErrors = new Map<number, string>();
    if (this.caps.plpgsqlCheck.available) {
      for (
        const r of await this.rows<{ oid: unknown; exec_count: unknown }>(
          `SELECT f.funcoid::pg_catalog.oid::bigint AS oid, f.exec_count::bigint AS exec_count
             FROM ${this.ext}.plpgsql_profiler_functions_all() f`,
        )
      ) {
        execCounts.set(num(r.oid), num(r.exec_count));
      }
      const plpgsql = universe.filter((f) => f.language === "plpgsql");
      const called = plpgsql.filter((f) =>
        (execCounts.get(f.oid) ?? 0) > 0 || callsOf(f.oid) > 0
      );
      // Branch ratio only for executed functions (never-executed ones read 1.0).
      for (const chunk of chunks(called.map((f) => f.oid), 100)) {
        try {
          for (
            const r of await this.rows<{ oid: unknown; branch_pct: unknown }>(
              `SELECT p.oid::bigint AS oid,
                      ${this.ext}.plpgsql_coverage_branches(p.oid::pg_catalog.regprocedure) AS branch_pct
                 FROM pg_catalog.pg_proc p WHERE p.oid IN (${
                chunk.join(", ")
              })`,
            )
          ) {
            branches.set(num(r.oid), num(r.branch_pct) * 100);
          }
        } catch {
          for (const oid of chunk) {
            try {
              const [r] = await this.rows<{ branch_pct: unknown }>(
                `SELECT ${this.ext}.plpgsql_coverage_branches(${oid}::pg_catalog.oid::pg_catalog.regprocedure) AS branch_pct`,
              );
              branches.set(oid, num(r.branch_pct) * 100);
            } catch {
              // branch coverage is informational only
            }
          }
        }
      }
      // Per-statement rows for every PL/pgSQL function: never-executed ones
      // still yield one row per statement with exec_stmts 0/NULL.
      const statementsSql = (oids: number[]) =>
        `SELECT p.oid::bigint AS oid, s.lineno, COALESCE(s.exec_stmts, 0)::bigint AS exec_stmts
           FROM pg_catalog.pg_proc p
           CROSS JOIN LATERAL ${this.ext}.plpgsql_profiler_function_statements_tb(p.oid::pg_catalog.regprocedure) s
          WHERE p.oid IN (${oids.join(", ")})`;
      const addRows = (
        rows: { oid: unknown; lineno: unknown; exec_stmts: unknown }[],
      ) => {
        for (const r of rows) {
          const oid = num(r.oid);
          const list = statements.get(oid) ?? [];
          list.push({ lineno: num(r.lineno), exec: num(r.exec_stmts) });
          statements.set(oid, list);
        }
      };
      for (const chunk of chunks(plpgsql.map((f) => f.oid), 100)) {
        try {
          addRows(await this.rows(statementsSql(chunk)));
        } catch {
          for (const oid of chunk) {
            try {
              addRows(await this.rows(statementsSql([oid])));
            } catch (error) {
              lineErrors.set(oid, errorMessage(error));
            }
          }
        }
      }
    }

    const sourceIndex = await buildSourceIndex();
    const functions: FunctionCoverage[] = universe.map((f) => {
      const calls = this.caps.trackFunctions.enabled ? callsOf(f.oid) : null;
      const execCount =
        this.caps.plpgsqlCheck.available && f.language === "plpgsql"
          ? (execCounts.get(f.oid) ?? 0)
          : null;
      let called: boolean | null;
      if (calls === null && execCount === null) called = null;
      else called = (calls ?? 0) > 0 || (execCount ?? 0) > 0;

      const source = locateFunction(sourceIndex, f);
      const stmtRows = statements.get(f.oid);
      let stmts: FunctionCoverage["statements"] = null;
      let lineHits: [number, number][] | null = null;
      const uncovered: number[] = [];
      if (stmtRows && stmtRows.length > 0) {
        const executed = stmtRows.filter((s) => s.exec > 0).length;
        stmts = {
          total: stmtRows.length,
          executed,
          pct: (executed / stmtRows.length) * 100,
        };
        if (source) {
          const byLine = new Map<number, number>();
          for (const s of stmtRows) {
            if (s.lineno <= 0) continue;
            const line = source.bodyLine + s.lineno - 1;
            byLine.set(line, Math.max(byLine.get(line) ?? 0, s.exec));
          }
          lineHits = [...byLine.entries()].sort((a, b) => a[0] - b[0]);
          for (const [line, hits] of lineHits) {
            if (hits === 0) uncovered.push(line);
          }
        }
      }
      const generated = f.schema === "public" && (
        f.name === "_label" ||
        (f.name.endsWith("_label") && f.args.startsWith("rec ")) ||
        f.name.startsWith("compute_validate_") ||
        f.name.startsWith("select_rule_")
      );
      const result: FunctionCoverage = {
        oid: f.oid,
        schema: f.schema,
        name: f.name,
        args: f.args,
        language: f.language,
        kind: f.isTrigger
          ? "trigger"
          : f.prokind === "p"
          ? "procedure"
          : "function",
        securityDefiner: f.prosecdef,
        generated,
        calls,
        execCount,
        called,
        statements: stmts,
        branchesPct: branches.get(f.oid) ?? null,
        source,
        lineHits,
        uncoveredLines: uncovered,
      };
      const lineError = lineErrors.get(f.oid);
      if (lineError) result.lineDetailError = lineError;
      return result;
    });

    const tableCoverage: TableCoverage[] = tables.map((t) => {
      const b = this.before.tables.get(t.oid) ??
        { seq: 0, idx: 0, ins: 0, upd: 0, del: 0 };
      const a = after.tables.get(t.oid) ?? b;
      const seqScan = a.seq - b.seq;
      const idxScan = a.idx - b.idx;
      const inserts = a.ins - b.ins;
      const updates = a.upd - b.upd;
      const deletes = a.del - b.del;
      return {
        oid: t.oid,
        schema: t.schema,
        name: t.name,
        policies: t.policies,
        touched: seqScan + idxScan + inserts + updates + deletes > 0,
        seqScan,
        idxScan,
        inserts,
        updates,
        deletes,
      };
    });

    const measurable = functions.filter((f) => f.called !== null);
    const calledCount = measurable.filter((f) => f.called).length;
    const stmtTotal = functions.reduce(
      (s, f) => s + (f.statements?.total ?? 0),
      0,
    );
    const stmtExecuted = functions.reduce(
      (s, f) => s + (f.statements?.executed ?? 0),
      0,
    );
    const touched = tableCoverage.filter((t) => t.touched).length;
    const functionPct = pct(calledCount, measurable.length);

    return {
      version: 1,
      generatedAt: new Date().toISOString(),
      database: maskUrl(databaseUrl),
      capabilities: this.caps,
      run,
      totals: {
        functions: {
          total: functions.length,
          measurable: measurable.length,
          called: calledCount,
          pct: functionPct,
          neverCalled: measurable.length - calledCount,
          unmeasurable: functions.length - measurable.length,
          generated: functions.filter((f) => f.generated).length,
        },
        statements: this.caps.plpgsqlCheck.available && stmtTotal > 0
          ? {
            total: stmtTotal,
            executed: stmtExecuted,
            pct: (stmtExecuted / stmtTotal) * 100,
          }
          : null,
        tables: {
          total: tableCoverage.length,
          touched,
          pct: pct(touched, tableCoverage.length),
        },
      },
      threshold: {
        min: this.opts.min,
        metric: "functions",
        passed: this.opts.min === undefined
          ? null
          : functionPct !== null && functionPct >= this.opts.min,
      },
      functions,
      tables: tableCoverage,
    };
  }
}

// ---------------------------------------------------------------------------
// Reports
// ---------------------------------------------------------------------------

function signature(f: FunctionCoverage): string {
  return `${f.schema}.${f.name}(${f.args})`;
}

function tags(f: FunctionCoverage): string {
  const t: string[] = [];
  if (f.language !== "plpgsql") t.push(f.language);
  if (f.kind === "trigger") t.push("trigger");
  if (f.securityDefiner) t.push("definer");
  if (f.generated) t.push("generated");
  return t.length > 0 ? ` [${t.join(", ")}]` : "";
}

function sourceRef(f: FunctionCoverage): string {
  return f.source ? ` - ${f.source.file}:${f.source.headerLine}` : "";
}

export function renderUncoveredMarkdown(s: CoverageSummary): string {
  const out: string[] = [];
  const c = s.capabilities;
  out.push("# Test coverage: uncovered code");
  out.push("");
  out.push(`Generated: ${s.generatedAt}`);
  out.push(`Database: ${s.database}`);
  out.push(
    `Universe: ${
      c.universe.mode === "extension"
        ? `extension ${c.universe.extension}`
        : `schemas ${c.universe.schemas?.join(", ")}`
    } (${s.totals.functions.total} functions, ${s.totals.tables.total} tables)`,
  );
  out.push(
    `Capabilities: ${
      c.plpgsqlCheck.available
        ? `plpgsql_check ${c.plpgsqlCheck.version} in schema ${c.plpgsqlCheck.schema}`
        : `plpgsql_check unavailable (${c.plpgsqlCheck.reason ?? "unknown"})`
    }; track_functions ${c.trackFunctions.enabled ? "on" : "off"}${
      c.trackFunctions.reason ? ` (${c.trackFunctions.reason})` : ""
    }`,
  );
  out.push(
    `Run: ${s.run.files} files, tests ${
      s.run.testsPassed ? "passed" : "FAILED"
    }${
      s.run.partial
        ? ` (partial:${s.run.filter ? ` filter ${s.run.filter}` : ""}${
          s.run.stoppedEarly ? " stopped early" : ""
        })`
        : ""
    }`,
  );
  out.push("");
  out.push("## Totals");
  out.push("");
  const tf = s.totals.functions;
  out.push(
    `- Functions: ${tf.called}/${tf.measurable} called (${
      fmtPct(tf.pct)
    }); never called ${tf.neverCalled}, not measurable ${tf.unmeasurable}, generated ${tf.generated}`,
  );
  if (s.totals.statements) {
    const ts = s.totals.statements;
    out.push(
      `- PL/pgSQL statements: ${ts.executed}/${ts.total} executed (${
        fmtPct(ts.pct)
      })`,
    );
  } else {
    out.push("- PL/pgSQL statements: not measured");
  }
  out.push(
    `- Tables: ${s.totals.tables.touched}/${s.totals.tables.total} touched (${
      fmtPct(s.totals.tables.pct)
    })`,
  );
  if (s.threshold.min !== undefined) {
    out.push(
      `- Threshold: functions ${fmtPct(tf.pct)} ${
        s.threshold.passed ? ">=" : "<"
      } ${s.threshold.min}% (${s.threshold.passed ? "PASS" : "FAIL"})`,
    );
  }

  const never = s.functions.filter((f) => f.called === false);
  out.push("");
  out.push(`## Functions never called (${never.length})`);
  for (const schema of [...new Set(never.map((f) => f.schema))].sort()) {
    out.push("");
    out.push(`### ${schema}`);
    out.push("");
    for (const f of never.filter((f) => f.schema === schema)) {
      out.push(`- ${f.name}(${f.args})${tags(f)}${sourceRef(f)}`);
    }
  }

  const partial = s.functions
    .filter((f) => f.called && f.statements && f.statements.pct < 100)
    .sort((a, b) => a.statements!.pct - b.statements!.pct);
  out.push("");
  out.push(
    `## Partially covered PL/pgSQL functions (${partial.length}, sorted by statement coverage)`,
  );
  out.push("");
  for (const f of partial) {
    const st = f.statements!;
    const branch = f.branchesPct !== null
      ? `, branches ${fmtPct(f.branchesPct)}`
      : "";
    const lines = f.uncoveredLines.length > 0
      ? `; uncovered lines ${compressRanges(f.uncoveredLines)}`
      : f.source
      ? ""
      : "; source not mapped";
    out.push(
      `- ${signature(f)}${tags(f)}: ${st.executed}/${st.total} statements (${
        fmtPct(st.pct)
      })${branch}${sourceRef(f)}${lines}`,
    );
  }

  const errors = s.functions.filter((f) => f.lineDetailError);
  if (errors.length > 0) {
    out.push("");
    out.push(`## Statement detail unavailable (${errors.length})`);
    out.push("");
    for (const f of errors) {
      out.push(`- ${signature(f)}: ${f.lineDetailError}`);
    }
  }

  const untouched = s.tables.filter((t) => !t.touched);
  out.push("");
  out.push(`## Tables never touched (${untouched.length})`);
  out.push("");
  for (const t of untouched) {
    out.push(`- ${t.schema}.${t.name} (${t.policies} policies)`);
  }

  const unmeasurable = s.functions.filter((f) => f.called === null);
  if (unmeasurable.length > 0) {
    out.push("");
    out.push(`## Not measurable on this connection (${unmeasurable.length})`);
    out.push("");
    for (const f of unmeasurable) {
      out.push(`- ${signature(f)}${tags(f)}${sourceRef(f)}`);
    }
  }

  out.push("");
  out.push("## How to read this");
  out.push("");
  out.push(
    "- A function counts as called when pg_stat_user_functions saw a call or the plpgsql_check profiler executed it during this run.",
  );
  out.push(
    "- SQL-language functions that the planner inlines are never counted by pg_stat_user_functions; check the test files before treating one as untested.",
  );
  out.push(
    "- Never-called PL/pgSQL functions are reported with 0 executed statements even though plpgsql_coverage_statements() would report 100% for them.",
  );
  out.push(
    "- Statement coverage counts profiler statements; a line with several statements is covered when any of them ran.",
  );
  out.push("");
  return out.join("\n");
}

export function renderLcov(s: CoverageSummary): string {
  const byFile = new Map<string, FunctionCoverage[]>();
  for (const f of s.functions) {
    if (!f.source) continue;
    const list = byFile.get(f.source.file) ?? [];
    list.push(f);
    byFile.set(f.source.file, list);
  }
  const out: string[] = [];
  for (const file of [...byFile.keys()].sort()) {
    const fns = byFile.get(file)!;
    out.push("TN:");
    out.push(`SF:${file}`);
    let fnHit = 0;
    for (const f of fns) {
      const name = signature(f).replace(/,/g, ";");
      out.push(`FN:${f.source!.headerLine},${name}`);
      if (f.called === null) continue;
      const hits = Math.max(f.calls ?? 0, f.execCount ?? 0);
      out.push(`FNDA:${hits},${name}`);
      if (hits > 0) fnHit++;
    }
    out.push(`FNF:${fns.length}`);
    out.push(`FNH:${fnHit}`);
    const lines = new Map<number, number>();
    for (const f of fns) {
      for (const [line, hits] of f.lineHits ?? []) {
        lines.set(line, Math.max(lines.get(line) ?? 0, hits));
      }
    }
    let lh = 0;
    for (const line of [...lines.keys()].sort((a, b) => a - b)) {
      const hits = lines.get(line)!;
      out.push(`DA:${line},${hits}`);
      if (hits > 0) lh++;
    }
    out.push(`LF:${lines.size}`);
    out.push(`LH:${lh}`);
    out.push("end_of_record");
  }
  return out.join("\n") + (out.length > 0 ? "\n" : "");
}

/** Writes summary.json, uncovered.md and lcov.info; returns the paths written. */
export async function writeCoverageReports(
  summary: CoverageSummary,
  outDir: string,
): Promise<string[]> {
  await Deno.mkdir(outDir, { recursive: true });
  const files: [string, string][] = [
    [`${outDir}/summary.json`, JSON.stringify(summary, null, 2) + "\n"],
    [`${outDir}/uncovered.md`, renderUncoveredMarkdown(summary)],
    [`${outDir}/lcov.info`, renderLcov(summary)],
  ];
  for (const [path, content] of files) {
    await Deno.writeTextFile(path, content);
  }
  return files.map(([path]) => path);
}

export function printCoverageSummary(
  s: CoverageSummary,
  tap: boolean,
  reportPaths: string[],
): void {
  const p = tap ? "# " : "";
  const tf = s.totals.functions;
  const lines: string[] = [];
  lines.push("");
  lines.push(
    `  Coverage (plpgsql_check profiler + pg_stat_user_functions)${
      s.run.partial ? " - partial run" : ""
    }`,
  );
  lines.push(
    `    Functions:  ${tf.called}/${tf.measurable} called (${
      fmtPct(tf.pct)
    })   ${tf.neverCalled} never called, ${tf.unmeasurable} not measurable, ${tf.generated} generated`,
  );
  if (s.totals.statements) {
    const ts = s.totals.statements;
    lines.push(
      `    Statements: ${ts.executed}/${ts.total} executed (${fmtPct(ts.pct)})`,
    );
  } else {
    lines.push(`    Statements: not measured (plpgsql_check unavailable)`);
  }
  lines.push(
    `    Tables:     ${s.totals.tables.touched}/${s.totals.tables.total} touched (${
      fmtPct(s.totals.tables.pct)
    })`,
  );
  if (reportPaths.length > 0) {
    lines.push(`    Reports:    ${reportPaths.join(", ")}`);
  }
  if (s.threshold.min !== undefined) {
    lines.push(
      `    Threshold:  functions ${fmtPct(tf.pct)} ${
        s.threshold.passed ? ">=" : "<"
      } ${s.threshold.min}% (${s.threshold.passed ? "PASS" : "FAIL"})`,
    );
  }
  for (const line of lines) {
    console.log(line === "" ? (tap ? "#" : "") : `${p}${line}`);
  }
}

/** True unless a threshold was requested and not met (or not measurable). */
export function coverageGatePassed(s: CoverageSummary): boolean {
  return s.threshold.passed !== false;
}
