/**
 * Extension command implementation (CLI).
 *
 * Packages the core SQL migrations as a PostgreSQL extension — an *additional*
 * distribution channel for self-hosted PostgreSQL (see pgdocker/), alongside
 * the `migrate` deploy used for Neon/Supabase. It does not replace anything.
 *
 * It generates, into the output directory (default ./extension):
 *   - <name>.control            extension metadata (default_version, schema, ...)
 *   - <name>--<version>.sql      current full install (thin installer)
 *   - <name>--<prev>--<version>.sql  upgrade script (migrations added since prev)
 *   - versions.json             manifest of each version's migration set + hashes
 *   - META.json                 PGXN distribution manifest
 *   - Makefile                  PGXS makefile so self-hosters can `make install`
 *   - README.md                 install instructions
 *
 * Versioning follows the pgTAP model: a single current full install plus an
 * accumulated chain of upgrade scripts (so `ALTER EXTENSION ... UPDATE` works).
 * Because the `_core` migrations are append-only ordered deltas, both are derived
 * automatically — the upgrade script is just the migrations added since the prior
 * version (per versions.json); editing a released migration is detected and warned.
 *
 * SHAPE: a THIN INSTALLER, not a concatenation of the migrations.
 *
 * The script creates only the cluster roles, the `semantius` schema and that
 * schema's functions. Everything else — 52 relations, their triggers, policies
 * and seed rows — is created later by `semantius.migrate()`, which runs OUTSIDE
 * any extension script, so none of it becomes an extension member. That single
 * property is what makes a plain `pg_dump`/single-pass `pg_restore` work and
 * `DROP EXTENSION` harmless; see plans/pg_semantius-extension-rebuild.md.
 *
 * Install is therefore two statements:
 *   CREATE EXTENSION pg_semantius;
 *   SELECT semantius.migrate();
 *
 * The migration text is embedded VERBATIM in dollar-quoted EXECUTE blocks: no
 * rewriting, no lifting of CREATE EXTENSION (0010 creates pgcrypto itself,
 * inside migrate(), under a pinned `search_path = public`), no audit silencer,
 * no `pg_extension_config_dump` (there are no member tables to register).
 *
 * The schema is `semantius`, not `pg_semantius`: PostgreSQL reserves the `pg_`
 * prefix for system schemas. The extension keeps the `pg_semantius` name.
 */

import { getVersionsTableSql } from "@semantius/core";

interface MigrationFile {
  name: string;
  content: string;
}

/**
 * The schema the installer owns. NOT `pg_semantius`: PostgreSQL refuses
 * `CREATE SCHEMA pg_semantius` with `unacceptable schema name / The prefix
 * "pg_" is reserved for system schemas`. Extension names and custom GUC
 * classes may use the prefix; schema names may not.
 */
const INSTALLER_SCHEMA = "semantius";

/** Schemas the migrations create, checked for stray extension membership. */
const CORE_SCHEMAS = ["public", "common", "rbac", "audit", "pgmq"];

/** Extensions allowed to own objects in those schemas after migrate(). */
const MEMBERSHIP_ALLOWLIST = ["pgcrypto", "plpgsql_check"];

/** Dollar tag wrapping the migrate() body. */
const OUTER_TAG = "$pgsem_migrate_body$";

/** LF-normalises text (B13): local CRLF checkouts and CI's LF blobs must hash
 * and embed identically, or the release guard fails on line endings alone. */
function toLf(text: string): string {
  return text.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

/**
 * PGXN-style version manifest. Records, per released version, the set of source
 * migrations it contained and their content hashes — so a later run can compute
 * the upgrade delta and detect edits to already-released migrations.
 */
interface VersionsManifest {
  versions: Record<string, { files: Record<string, string> }>;
}

interface ExtensionOptions {
  apps: string;
  version: string;
  name: string;
  outputDir: string;
  /** Fail instead of warn when a released migration was edited or removed. */
  strict?: boolean;
}

export async function extensionCommand(
  options: ExtensionOptions,
): Promise<void> {
  const { version, name, outputDir } = options;
  const apps = !options.apps || options.apps.trim() === ""
    ? "_core"
    : options.apps;

  console.log(`Generating "${name}" extension v${version}...`);

  const appList = apps
    .split(",")
    .map((app) => app.trim())
    .filter((app) => app.length > 0);

  if (appList.length === 0) {
    console.error("No valid app names found");
    console.log("Provide comma-separated app names: app1,app2,app3");
    Deno.exit(1);
  }

  console.info(`Bundling app(s): ${appList.join(", ")}`);

  // Collect extension dependencies lifted out of the migration bodies.
  const requires = new Set<string>();

  const header = [
    `-- ${name} PostgreSQL extension`,
    `-- Version: ${version}`,
    `-- Generated by \`deno task extension\` from apps/{${
      appList.join(",")
    }}/migrations`,
    `-- DO NOT EDIT MANUALLY - regenerate after changing migrations.`,
    `--`,
    `-- Install:  CREATE EXTENSION ${name};`,
    `--           SELECT ${INSTALLER_SCHEMA}.migrate();`,
    ``,
    ``,
  ].join("\n");

  // Collect every migration (in filename order) with its raw + processed SQL.
  const migs: {
    app: string;
    name: string;
    content: string;
    processed: string;
    /** SHA-256 of the LF-normalised source, written into `_versions`. */
    checksum: string;
  }[] = [];

  for (const app of appList) {
    const appPath = `./apps/${app}`;
    try {
      const stat = await Deno.stat(appPath);
      if (!stat.isDirectory) {
        console.warn(`Path exists but is not a directory, skipping: ${app}`);
        continue;
      }
    } catch (error) {
      if (error instanceof Deno.errors.NotFound) {
        console.warn(`App not found, skipping: ${app}`);
        continue;
      }
      throw error;
    }

    const migrationFiles = await loadSqlFiles(app, "migrations");

    if (migrationFiles.length === 0) {
      console.info(`No migration files found for ${app}`);
      continue;
    }

    console.info(`Found ${migrationFiles.length} migration file(s) for ${app}`);

    for (const migration of migrationFiles) {
      if (!migration.content.trim()) {
        console.warn(`  Warning: Migration file ${migration.name} is empty`);
        continue;
      }
      // Verbatim, only LF-normalised. Nothing is lifted or rewritten: the
      // migrations run inside migrate(), not inside an extension script, so
      // 0010's own `CREATE EXTENSION pgcrypto` is legal there.
      const content = toLf(migration.content);
      lintMigration(`${app}/${migration.name}`, content);
      migs.push({
        app,
        name: migration.name,
        content,
        processed: content,
        checksum: await sha256hex(content),
      });
    }
  }

  if (migs.length === 0) {
    console.error("No migration SQL was bundled; nothing to generate.");
    Deno.exit(1);
  }

  // Every dollar tag the installer emits must be absent from every body, or
  // an embedded migration would terminate its own EXECUTE early.
  assertNoTagCollisions(migs);

  // Ensure output directory exists.
  await Deno.mkdir(outputDir, { recursive: true });

  // -- Versioning (pgTAP-style): one current full install + an accumulated
  //    chain of upgrade scripts, with a manifest tracking each version's
  //    migration set so deltas (and edits to released migrations) are detected.
  const manifestPath = `${outputDir}/versions.json`;
  const manifest = await loadManifest(manifestPath);

  const currentFiles: Record<string, string> = {};
  for (const m of migs) {
    currentFiles[`${m.app}/${m.name}`] = await sha256hex(m.content);
  }

  const prev = highestVersionBelow(version, manifest);
  // Members dropped from the bundle since `prev`. An upgrade script must DROP
  // them explicitly or they linger as members of the upgraded extension.
  const removedMembers: string[] = [];
  if (prev) {
    const prevFiles = manifest.versions[prev].files;
    const added = migs.filter((m) => !(`${m.app}/${m.name}` in prevFiles));
    const edited = migs.filter((m) => {
      const k = `${m.app}/${m.name}`;
      return k in prevFiles && prevFiles[k] !== currentFiles[k];
    });
    const removed = Object.keys(prevFiles).filter((k) => !(k in currentFiles));

    const strict = options.strict === true;
    const complain = (msg: string) =>
      strict ? console.error(msg) : console.warn(msg);
    const label = strict ? "Error" : "Warning";

    if (edited.length > 0) {
      complain(
        `${label}: ${edited.length} migration(s) released in ${prev} were ` +
          `edited in place:`,
      );
      for (const m of edited) complain(`  - ${m.app}/${m.name}`);
      complain(
        `These edits are NOT captured by the ${prev} -> ${version} upgrade. Add a ` +
          `new migration for the change rather than editing a released one.`,
      );
    }
    if (removed.length > 0) {
      complain(
        `${label}: ${removed.length} migration(s) from ${prev} no longer ` +
          `exist; the upgrade script cannot undo them:`,
      );
      for (const k of removed) complain(`  - ${k}`);
    }
    if (strict && (edited.length > 0 || removed.length > 0)) {
      console.error(
        "--strict: refusing to generate over an edited or removed released migration.",
      );
      Deno.exit(1);
    }

    const upgradeHeader = [
      `-- ${name} extension upgrade: ${prev} -> ${version}`,
      `-- Generated by \`deno task extension\` from migrations added since ${prev}.`,
      `-- DO NOT EDIT MANUALLY.`,
      ``,
      ``,
    ].join("\n");
    // An upgrade is the SAME installer, minus `CREATE SCHEMA` (the schema
    // already exists) and with CREATE OR REPLACE for the functions - replacing
    // a member of the same extension inside its own script is allowed. The
    // whole bundle is embedded, not just the delta: migrate() is idempotent
    // per migration via `_versions`, so one code path serves install, upgrade
    // and re-run.
    await Deno.writeTextFile(
      `${outputDir}/${name}--${prev}--${version}.sql`,
      toLf(
        upgradeHeader +
          renderInstaller(name, migs, { upgrade: true, removedMembers }),
      ),
    );
    console.info(
      `Wrote upgrade ${name}--${prev}--${version}.sql ` +
        `(${added.length} new migration(s), full bundle)`,
    );
  }

  // Record this version's migration set, then drop superseded full installs
  // (keep the current full install + the whole upgrade chain).
  manifest.versions[version] = { files: currentFiles };
  await Deno.writeTextFile(manifestPath, serializeManifest(manifest));
  const pruned = await pruneOldFullInstalls(outputDir, name, version);

  const controlPath = `${outputDir}/${name}.control`;
  const sqlPath = `${outputDir}/${name}--${version}.sql`;
  const makefilePath = `${outputDir}/Makefile`;
  const readmePath = `${outputDir}/README.md`;
  const metaPath = `${outputDir}/META.json`;

  await Deno.writeTextFile(
    controlPath,
    toLf(buildControlFile(name, version, requires)),
  );
  // Full install = header + the thin installer. No audit silencer, no seeded
  // `_versions` rows, no pg_dump registration: nothing here creates a table.
  const installSql = header + renderInstaller(name, migs, { upgrade: false });
  await Deno.writeTextFile(sqlPath, toLf(installSql));
  await Deno.writeTextFile(makefilePath, toLf(buildMakefile(name)));
  await Deno.writeTextFile(
    readmePath,
    toLf(buildReadme(name, version, requires)),
  );
  // META.json is the PGXN distribution manifest (https://pgxn.org/meta/spec.txt).
  await Deno.writeTextFile(
    metaPath,
    toLf(buildMetaJson(name, version, requires)),
  );

  const sqlBytes = new TextEncoder().encode(installSql).length;

  console.log("");
  console.log(`Extension generated in ${outputDir}/ (version ${version}):`);
  console.log(`  ${name}.control`);
  console.log(
    `  ${name}--${version}.sql  (${formatBytes(sqlBytes)})  [full install]`,
  );
  if (prev) console.log(`  ${name}--${prev}--${version}.sql  [upgrade]`);
  console.log(
    `  versions.json  (${Object.keys(manifest.versions).length} version(s))`,
  );
  console.log(`  Makefile, META.json, README.md`);
  for (const f of pruned) {
    console.log(`  (removed superseded full install ${f})`);
  }
  if (requires.size > 0) {
    console.log(`  requires: ${[...requires].sort().join(", ")}`);
  }
  console.log("");
  console.log(`Install:  CREATE EXTENSION ${name};`);
  console.log(`          SELECT ${INSTALLER_SCHEMA}.migrate();`);
  if (prev) {
    console.log(`Upgrade:  ALTER EXTENSION ${name} UPDATE TO '${version}';`);
    console.log(`          SELECT ${INSTALLER_SCHEMA}.migrate();`);
  }
  console.log("Extension generation completed!");
}

/** Escapes single quotes for safe embedding in a SQL string literal. */
function escapeSqlLiteral(text: string): string {
  return text.replace(/'/g, "''");
}

/** SHA-256 hex digest of a string (used to fingerprint migration sources). */
async function sha256hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text),
  );
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/** Compares dotted numeric versions (e.g. "0.2.0" vs "0.10.0"). */
function compareVersions(a: string, b: string): number {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const da = pa[i] ?? 0;
    const db = pb[i] ?? 0;
    if (da !== db) return da - db;
  }
  return 0;
}

/** Highest manifest version strictly below `target`, or undefined if none. */
function highestVersionBelow(
  target: string,
  manifest: VersionsManifest,
): string | undefined {
  const prior = Object.keys(manifest.versions)
    .filter((v) => compareVersions(v, target) < 0)
    .sort(compareVersions);
  return prior[prior.length - 1];
}

/** Loads the version manifest, returning an empty one if absent. */
async function loadManifest(path: string): Promise<VersionsManifest> {
  try {
    const parsed = JSON.parse(await Deno.readTextFile(path));
    return parsed && typeof parsed === "object" && parsed.versions
      ? parsed as VersionsManifest
      : { versions: {} };
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return { versions: {} };
    throw error;
  }
}

/** Serializes the manifest with versions and file keys sorted, for stable diffs. */
function serializeManifest(manifest: VersionsManifest): string {
  const versions: VersionsManifest["versions"] = {};
  for (const v of Object.keys(manifest.versions).sort(compareVersions)) {
    const files: Record<string, string> = {};
    for (const k of Object.keys(manifest.versions[v].files).sort()) {
      files[k] = manifest.versions[v].files[k];
    }
    versions[v] = { files };
  }
  return JSON.stringify({ versions }, null, 2) + "\n";
}

/**
 * Removes superseded full-install scripts (`<name>--<version>.sql`) from the
 * output dir, keeping only `keepVersion`. Upgrade scripts (`<name>--<a>--<b>.sql`,
 * which contain a second `--`) are left untouched. Returns the removed filenames.
 */
async function pruneOldFullInstalls(
  dir: string,
  name: string,
  keepVersion: string,
): Promise<string[]> {
  const prefix = `${name}--`;
  const removed: string[] = [];
  for await (const entry of Deno.readDir(dir)) {
    if (!entry.isFile) continue;
    if (!entry.name.startsWith(prefix) || !entry.name.endsWith(".sql")) {
      continue;
    }
    const mid = entry.name.slice(prefix.length, -".sql".length);
    if (mid.includes("--")) continue; // upgrade script — keep
    if (mid !== keepVersion) {
      await Deno.remove(`${dir}/${entry.name}`);
      removed.push(entry.name);
    }
  }
  return removed;
}

/** Builds the .control file contents. */
function buildControlFile(
  name: string,
  version: string,
  requires: Set<string>,
): string {
  const lines = [
    `# ${name} extension control file`,
    "# Generated by `deno task extension` - do not edit manually.",
    `comment = 'Semantius core: RBAC, RLS, data dictionary, and message queue'`,
    `default_version = '${version}'`,
    // Pins the extension to `public`: PostgreSQL then ignores the caller's
    // search_path for it and refuses `CREATE EXTENSION ... SCHEMA other` with
    // `extension "<name>" must be installed in schema "public"` (B2). `public`
    // always exists, so nothing is auto-created, and pg_dump emits
    // `WITH SCHEMA public`, which matches on restore.
    `schema = public`,
    `relocatable = false`,
    // The script creates cluster roles: superuser only.
    `superuser = true`,
    // 16 migrations carry UTF-8 text. This rejects a LATIN1 database; the
    // script's own pg_encoding_to_char check additionally rejects SQL_ASCII,
    // which would silently accept raw bytes (B9).
    `encoding = 'UTF8'`,
  ];

  // Deliberately NO `requires`. `CREATE EXTENSION ... CASCADE` would install
  // pgcrypto into the CALLER's default creation schema, and 0110 calls
  // gen_random_bytes/crypt/gen_salt unqualified under `search_path = public`,
  // so API keys would break in exactly B2's scenario. 0010 creates pgcrypto
  // itself, from inside migrate(), under the pinned search_path; META keeps it
  // as a runtime prereq and migrate()'s pre-flight refuses a misplaced one.
  void requires;

  return lines.join("\n") + "\n";
}

/** Builds a PGXS Makefile that installs every generated version script. */
function buildMakefile(name: string): string {
  return [
    `# Generated by \`deno task extension\` - do not edit manually.`,
    `# Installs the ${name} extension into PostgreSQL's extension directory.`,
    `#   make install   (uses pg_config; may need sudo)`,
    ``,
    `EXTENSION = ${name}`,
    `DATA = $(wildcard ${name}--*.sql)`,
    ``,
    `PG_CONFIG ?= pg_config`,
    `PGXS := $(shell $(PG_CONFIG) --pgxs)`,
    `include $(PGXS)`,
    ``,
  ].join("\n");
}

/**
 * Builds the PGXN distribution manifest (META.json, Meta Spec 1.0.0) so the
 * extension can be published to and installed from PGXN (`pgxn install pg_semantius`).
 * Version is kept in sync with the generated SQL on every run.
 */
function buildMetaJson(
  name: string,
  version: string,
  requires: Set<string>,
): string {
  // pgcrypto is a RUNTIME prerequisite but deliberately not a control-file
  // `requires`: CASCADE would install it into the caller's default creation
  // schema. migrate() creates it in `public` itself.
  const prereqRequires: Record<string, string> = {
    PostgreSQL: "18.0.0",
    pgcrypto: "0",
  };

  const meta = {
    name,
    abstract:
      "Database-first RBAC, RLS, data dictionary, and message queue for PostgreSQL",
    description:
      "Semantius core packaged as a PostgreSQL extension: role-based access " +
      "control, row-level security, a semantic data dictionary, and a message " +
      "queue. An alternative to deploying the migrations with the Semantius CLI.",
    version,
    maintainer: ["adenin TECHNOLOGIES <support@adenin.com>"],
    license: "mit",
    // "testing" until a version is actually released; PGXN readers use
    // this to decide whether a build is meant for production (B10).
    release_status: "testing",
    provides: {
      [name]: {
        abstract:
          "Semantius core: RBAC, RLS, data dictionary, and message queue",
        file: `${name}--${version}.sql`,
        docfile: "README.md",
        version,
      },
    },
    prereqs: {
      runtime: {
        requires: prereqRequires,
      },
    },
    resources: {
      homepage: "https://github.com/semantius/semantius",
      bugtracker: {
        web: "https://github.com/semantius/semantius/issues",
      },
      repository: {
        url: "https://github.com/semantius/semantius.git",
        web: "https://github.com/semantius/semantius",
        type: "git",
      },
    },
    generated_by: "deno task extension",
    // PGXN reads this from the archive; the file is hand-maintained in
    // extension/CHANGES.md and copied into the archive by the release job. It
    // carries no build date, so the release guard's diff stays stable.
    no_index: { file: ["CHANGES.md"] },
    "meta-spec": {
      version: "1.0.0",
      url: "https://pgxn.org/meta/spec.txt",
    },
    tags: [
      "rbac",
      "rls",
      "row level security",
      "data dictionary",
      "queue",
      "security",
    ],
  };

  // Record extension dependencies (e.g. pgcrypto) as runtime prereqs too.
  for (const dep of [...requires].sort()) {
    prereqRequires[dep] = "0";
  }

  return JSON.stringify(meta, null, 2) + "\n";
}

/**
 * Builds the CONSUMER README shipped inside the PGXN archive (B8).
 *
 * Consumer-only: it documents installing, upgrading, backing up, restoring and
 * uninstalling a released build. Repo paths, deno tasks and harness scripts
 * belong in the repository README, not here - a reader of the archive has
 * none of them.
 */
function buildReadme(
  name: string,
  version: string,
  requires: Set<string>,
): string {
  const S = INSTALLER_SCHEMA;
  void requires; // dependencies are documented inline, not via control `requires`
  return `# ${name} ${version}

Semantius core for PostgreSQL: role-based access control, row-level security,
a semantic data dictionary, and a message queue.

## Install

Two statements, as a superuser, in a UTF8 database:

\`\`\`sql
CREATE EXTENSION ${name};
SELECT ${S}.migrate();
\`\`\`

Do **not** use \`CASCADE\`. \`CREATE EXTENSION\` creates only the cluster roles,
the \`${S}\` schema and its functions. \`${S}.migrate()\` then installs the
core schema - tables, functions, triggers, policies and seed rows - as
**ordinary objects**. They are deliberately *not* extension members, which is
what makes a plain backup, a single-pass restore and a harmless
\`DROP EXTENSION\` possible.

\`pgcrypto\` is a runtime prerequisite. \`${S}.migrate()\` creates it in
\`public\`, where the API-key code needs it; if it is already installed in
another schema the install refuses with a hint.

## Upgrade

\`\`\`sql
ALTER EXTENSION ${name} UPDATE;
SELECT ${S}.migrate();
\`\`\`

\`ALTER EXTENSION ... UPDATE\` replaces the installer functions; \`migrate()\`
applies whatever is new. Both are safe to re-run: \`migrate()\` is idempotent
per migration. \`SELECT * FROM ${S}.pending()\` lists what a \`migrate()\`
would apply; \`SELECT * FROM ${S}.status()\` reports drift.

## Functions

| Function | Purpose |
|---|---|
| \`${S}.migrate()\` | Applies the bundled migrations. Superuser only, idempotent, one transaction. |
| \`${S}.pending()\` | Bundled migrations not yet applied. Works before the first migrate(). |
| \`${S}.version()\` | Version of the installed bundle. |
| \`${S}.status()\` | Applied/pending counts, unknown or changed migrations, ownership and default-ACL drift. |

\`\\dx\` shows the *installer's* version, which is not necessarily the state of
the installed schema; \`${S}.status()\` is the authority.

## Backup and restore

Backup is a plain dump and restore is a single pass. No flags, no environment
variables, no ordering rules:

\`\`\`sh
pg_dump -Fc -d appdb -f appdb.dump          # as a superuser or a BYPASSRLS role
createdb -T template0 newdb
pg_restore -d newdb appdb.dump              # one pass, same cluster or a fresh one
\`\`\`

\`-Fp\` piped to psql, \`-j\` and \`-1\` all work too. Facts worth knowing:

- Restore into an **empty** database. Do not run \`migrate()\` first: the dump's
  own \`CREATE EXTENSION\` recreates the roles and functions.
- Restore as a superuser **named like the installing one** (\`postgres\` in the
  shipped images) and **not** with \`--no-owner\`. A differently named superuser
  still gets working data, but the schemas and event triggers stay owned by the
  restorer and the installer's default-privilege entries are lost, so functions
  created by hand later would be PUBLIC-executable. \`${S}.status()\` reports
  this.
- On a **fresh cluster** the four roles are recreated by the dump's
  \`CREATE EXTENSION\`, but they are NOLOGIN and without passwords: rerun your
  deployment's login step.
- If the extension files are **absent** on the target server, the dump's
  \`CREATE EXTENSION\` and \`COMMENT ON EXTENSION\` fail and everything else
  restores, so the database still works. On a fresh cluster the four roles are
  then missing too: create them first (\`pg_dumpall --globals-only\`).
- A dump taken **after** \`DROP EXTENSION\` carries no \`CREATE EXTENSION\`, so
  the same rule applies.
- UTF8 databases only. LATIN1 and SQL_ASCII are refused at install time.

## Uninstall

\`DROP EXTENSION ${name}\` removes the \`${S}\` schema and its functions and
**nothing else** - never CASCADE, never any data. To remove Semantius
completely, in this order (step 3 **deletes all data**):

\`\`\`sql
DROP EXTENSION ${name};
DROP EVENT TRIGGER track_ddl_changes, pgrst_ddl_watch, pgrst_drop_watch;
DROP OWNED BY semantius_owner CASCADE;      -- deletes all Semantius data
DROP SCHEMA IF EXISTS common, rbac, audit, pgmq CASCADE;
DROP TABLE IF EXISTS public._versions;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM semantius_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE USAGE, SELECT ON SEQUENCES FROM semantius_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO PUBLIC;
DROP OWNED BY semantius_user, authenticated, semantius_authenticator;
-- only if no other database in this cluster uses them:
DROP ROLE semantius_user, authenticated, semantius_authenticator, semantius_owner;
\`\`\`

The event triggers go first because they fire on every drop below them.

The last statement leaves one \`pg_default_acl\` row behind
(\`public | FUNCTIONS | {=X/postgres}\`). That is the built-in default written
out explicitly rather than a leftover privilege: a function created afterwards
gets the default ACL and PUBLIC can execute it, exactly as in a database that
never had ${name} installed.

## Roles

Created by \`CREATE EXTENSION\` (cluster-wide, never dropped with it). All four
are NOLOGIN and passwordless; grant LOGIN and a password per environment.

| Role | Purpose |
|---|---|
| \`semantius_owner\` | Owns the core objects; the identity the SECURITY DEFINER dictionary code runs as. NOLOGIN NOSUPERUSER NOINHERIT BYPASSRLS. |
| \`semantius_user\` | The request role. Subject to RLS. |
| \`authenticated\` | Holds \`semantius_user\`; what an authenticated session acts as. |
| \`semantius_authenticator\` | Session-mode login role; NOINHERIT, can only \`SET ROLE authenticated\`. |

An existing role is verified rather than adopted: if one of these already
exists with unexpected attributes, or \`semantius_owner\` already has members,
the install refuses.

## Session settings the caller controls

\`migrate()\` pins \`search_path\`, \`standard_conforming_strings\` and
\`check_function_bodies\`, and forces \`session_replication_role = origin\`, so
an unusual session cannot change what gets installed. It still fails, by
design, under \`default_transaction_read_only\`, a \`statement_timeout\` or
\`lock_timeout\` shorter than the install, or an isolation level above read
committed.

## Runtime configuration

The code reads these settings from the session:

| Setting | Set by |
|---|---|
| \`request.jwt.claims\` | PostgREST or your app tier, per request |
| \`request.jwt.claim.sub\`, \`request.jwt.claim.email\`, \`request.jwt.claim.role\`, \`request.jwt.claim.name\`, \`request.jwt.claim.given_name\`, \`request.jwt.claim.family_name\`, \`request.jwt.claim.aud\` | the same, one GUC per claim (Neon/Supabase style) |
| \`app.current_user_id\`, \`app.user_permissions\`, \`app.oauth_scopes\`, \`app.current_external_id\`, \`app.context_initialized\`, \`app.bumping_module_version\`, \`app.bearer_cache_notice\` | the RBAC code itself, per transaction |
| \`dd.table_rename\` | the data dictionary, during a table rename |

DDL emits \`NOTIFY pgrst, 'reload schema'\` so PostgREST reloads its cache, and
the audit event trigger records DDL in \`public.audit_ddl_logs\`.

## Errors

| SQLSTATE | Message |
|---|---|
| - | \`permission denied to create extension "${name}"\` / \`Must be superuser to create this extension\` |
| - | \`extension "${name}" must be installed in schema "public"\` |
| 42501 | \`permission denied for schema ${S}\` |
| 42501 | \`${S}.migrate() must be run by a superuser (current_user is ...)\` |
| 55000 | \`${name} requires a UTF8 database\` |
| 55000 | \`the pgmq extension is installed; ${name} vendors its own pgmq schema\` |
| 55000 | \`pgcrypto must be installed in schema public\` |
| 55000 | \`existing role semantius_owner has unexpected attributes\` |
| 55000 | \`${S}.migrate() cannot run inside a CREATE/ALTER EXTENSION script\` |

## Requirements

PostgreSQL 18 (the only tested version), a UTF8 database, and superuser rights
to install. Security model and reporting: see \`SECURITY.md\` in this archive.
`;
}

/** Loads all .sql files from apps/{folderName}/{subfolder}/ sorted ascending. */
async function loadSqlFiles(
  folderName: string,
  subfolder: string,
): Promise<MigrationFile[]> {
  const sqlPath = `./apps/${folderName}/${subfolder}`;

  try {
    const sqlFileNames: string[] = [];

    for await (const dirEntry of Deno.readDir(sqlPath)) {
      if (dirEntry.isFile && dirEntry.name.endsWith(".sql")) {
        sqlFileNames.push(dirEntry.name);
      }
    }

    sqlFileNames.sort();

    const migrations: MigrationFile[] = [];
    for (const fileName of sqlFileNames) {
      const filePath = `${sqlPath}/${fileName}`;
      const content = await Deno.readTextFile(filePath);
      migrations.push({
        name: fileName.replace(/\.sql$/, ""),
        content,
      });
    }

    return migrations;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      console.info(`No ${subfolder} folder found at: ${sqlPath}`);
      return [];
    }
    console.error(
      `Error reading ${subfolder} folder ${sqlPath}:`,
      error instanceof Error ? error.message : String(error),
    );
    return [];
  }
}

/** Human-readable byte size. */
function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/**
 * Splits SQL into top-level statements, ignoring semicolons inside comments,
 * single-quoted literals and dollar-quoted bodies (removed spans become a
 * space, so statement boundaries survive).
 *
 * A naive scan cannot tell a standalone `SET search_path = ...` from the
 * identically spelled ATTRIBUTE CLAUSE of a CREATE FUNCTION, which these
 * migrations write at column 0 (0060, 0145, 0170, ...).
 */
function topLevelStatements(sql: string): string[] {
  let out = "";
  let i = 0;
  while (i < sql.length) {
    const two = sql.slice(i, i + 2);
    if (two === "--") {
      const nl = sql.indexOf("\n", i);
      i = nl === -1 ? sql.length : nl;
      out += " ";
      continue;
    }
    if (two === "/*") {
      let depth = 1;
      let j = i + 2;
      while (j < sql.length && depth > 0) {
        if (sql.slice(j, j + 2) === "/*") {
          depth++;
          j += 2;
        } else if (sql.slice(j, j + 2) === "*/") {
          depth--;
          j += 2;
        } else j++;
      }
      i = j;
      out += " ";
      continue;
    }
    if (sql[i] === "'") {
      let j = i + 1;
      while (j < sql.length) {
        if (sql[j] === "'" && sql[j + 1] === "'") j += 2;
        else if (sql[j] === "'") {
          j++;
          break;
        } else j++;
      }
      i = j;
      out += " ";
      continue;
    }
    const dollar = /^\$([A-Za-z_][A-Za-z0-9_]*)?\$/.exec(sql.slice(i));
    if (dollar) {
      const tag = dollar[0];
      const end = sql.indexOf(tag, i + tag.length);
      i = end === -1 ? sql.length : end + tag.length;
      out += " ";
      continue;
    }
    out += sql[i];
    i++;
  }
  return out.split(";").map((x) => x.trim()).filter((x) => x.length > 0);
}

/**
 * Refuses constructs that are safe in the CLI's per-file transactions but not
 * in migrate(), which runs all 34 migrations in ONE transaction:
 *   - a top-level SET/RESET would leak into every later migration;
 *   - transaction control would break the all-or-nothing install;
 *   - CREATE INDEX CONCURRENTLY and COPY ... FROM STDIN cannot run there.
 * None of these exist today; the lint keeps it that way.
 */
function lintMigration(label: string, content: string): void {
  const banned =
    /^(SET\s+(?!LOCAL\b)|RESET\b|BEGIN\b|COMMIT\b|ROLLBACK\b|START\s+TRANSACTION|SAVEPOINT\b|CREATE\s+INDEX\s+CONCURRENTLY|COPY\b[\s\S]*\bFROM\s+STDIN)/i;
  for (const statement of topLevelStatements(content)) {
    if (banned.test(statement)) {
      console.error(
        `Migration lint failed in ${label}: ${
          statement.replace(/\s+/g, " ").slice(0, 80)
        }`,
      );
      console.error(
        "migrate() applies every migration in one transaction, so this would " +
          "affect the migrations that follow it.",
      );
      Deno.exit(1);
    }
  }
}

/** The dollar tag wrapping one embedded migration. */
function migrationTag(m: { app: string; name: string }): string {
  return `$pgsem_${m.app.replace(/[^A-Za-z0-9_]/g, "_")}_${
    m.name.replace(/[^A-Za-z0-9_]/g, "_")
  }$`;
}

/**
 * Every dollar tag the installer emits must be absent from every migration
 * body, or an embedded migration would terminate its own EXECUTE early and the
 * script would fail in a way that is very hard to read.
 */
function assertNoTagCollisions(
  migs: { app: string; name: string; content: string }[],
): void {
  const tags = [OUTER_TAG, ...migs.map(migrationTag)];
  for (const m of migs) {
    for (const tag of tags) {
      if (m.content.includes(tag)) {
        console.error(
          `Dollar tag ${tag} occurs inside ${m.app}/${m.name}; it cannot be ` +
            "used to quote the embedded migration.",
        );
        Deno.exit(1);
      }
    }
  }
}

/**
 * Renders the whole extension script: roles, schema, and the functions.
 *
 * `upgrade` omits `CREATE SCHEMA` (it already exists) and uses CREATE OR
 * REPLACE, which is allowed for a member of the same extension inside its own
 * script. `removedMembers` are dropped so they do not linger as members.
 */
function renderInstaller(
  name: string,
  migs: {
    app: string;
    name: string;
    content: string;
    checksum: string;
  }[],
  opts: { upgrade: boolean; removedMembers?: string[] },
): string {
  const S = INSTALLER_SCHEMA;
  const orReplace = opts.upgrade ? "CREATE OR REPLACE" : "CREATE";
  const names = migs.map((m) => `${m.app}.${m.name}`);

  const steps = migs.map((m) => {
    const tag = migrationTag(m);
    const versionName = `${m.app}.${m.name}`;
    return `
  IF NOT EXISTS (SELECT 1 FROM public._versions WHERE name = '${
      escapeSqlLiteral(versionName)
    }') THEN
    RAISE NOTICE '${name}: applying ${escapeSqlLiteral(versionName)}';
    BEGIN
      EXECUTE ${tag}${m.content}${tag};
    EXCEPTION WHEN OTHERS THEN
      -- Without this the whole embedded migration is reported as CONTEXT.
      GET STACKED DIAGNOSTICS
        v_state  = RETURNED_SQLSTATE,
        v_msg    = MESSAGE_TEXT,
        v_detail = PG_EXCEPTION_DETAIL,
        v_hint   = PG_EXCEPTION_HINT,
        v_ctx    = PG_EXCEPTION_CONTEXT;
      RAISE EXCEPTION 'migration % failed: % (SQLSTATE %)',
            '${escapeSqlLiteral(versionName)}', v_msg, v_state
        USING DETAIL = coalesce(v_detail, ''),
              HINT   = coalesce(nullif(v_hint, ''), 'at: ' ||
                       split_part(coalesce(v_ctx, ''), E'\\n', 1));
    END;
    INSERT INTO public._versions (name, checksum)
      VALUES ('${escapeSqlLiteral(versionName)}', '${m.checksum}');
    v_applied := v_applied + 1;
  ELSE
    v_skipped := v_skipped + 1;
  END IF;
`;
  }).join("");

  const drops = (opts.removedMembers ?? [])
    .map((sig) => `DROP FUNCTION IF EXISTS ${sig};\n`)
    .join("");

  return `-- =====================================================
-- Thin installer. This script creates ONLY cluster roles, the ${S} schema
-- and its functions. The 52 core relations, their triggers, policies and seed
-- rows are created by ${S}.migrate(), which runs OUTSIDE any extension
-- script, so none of them becomes an extension member. That is what makes a
-- plain pg_dump / single-pass pg_restore work and DROP EXTENSION harmless.
-- =====================================================

-- 1. Database encoding. The control file's encoding = 'UTF8' rejects LATIN1,
--    but a SQL_ASCII database would accept raw bytes, so check explicitly.
DO $pgsem_encoding$
BEGIN
  IF (SELECT pg_catalog.pg_encoding_to_char(encoding)
        FROM pg_catalog.pg_database WHERE datname = current_database())
     <> 'UTF8' THEN
    RAISE EXCEPTION '${name} requires a UTF8 database (this one is %)',
      (SELECT pg_catalog.pg_encoding_to_char(encoding)
         FROM pg_catalog.pg_database WHERE datname = current_database())
      USING ERRCODE = '55000',
            HINT = 'createdb -T template0 -E UTF8';
  END IF;
END
$pgsem_encoding$;

-- 2. Cluster roles. Roles are shared objects: never extension members, never
--    dropped by DROP EXTENSION. They are created here so that the
--    CREATE EXTENSION inside a RESTORED DUMP provisions them before the dump's
--    own GRANT / CREATE POLICY / OWNER TO statements run.
--
--    An existing role is VERIFIED, not adopted: otherwise a CREATEROLE user
--    could pre-create semantius_owner with itself as a member and would own
--    every core table after a restore.
DO $pgsem_roles$
DECLARE
  r pg_catalog.pg_roles%ROWTYPE;
BEGIN
  SELECT * INTO r FROM pg_catalog.pg_roles WHERE rolname = 'semantius_owner';
  IF NOT FOUND THEN
    CREATE ROLE semantius_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
      NOREPLICATION NOINHERIT BYPASSRLS;
    COMMENT ON ROLE semantius_owner IS
      'Owner of the Semantius core objects and the role its SECURITY DEFINER dictionary code runs as.';
  ELSE
    IF r.rolsuper OR r.rolcanlogin OR r.rolcreaterole OR r.rolcreatedb
       OR r.rolreplication OR r.rolinherit OR NOT r.rolbypassrls THEN
      RAISE EXCEPTION 'existing role semantius_owner has unexpected attributes'
        USING ERRCODE = '55000',
              DETAIL = 'expected NOSUPERUSER NOLOGIN NOCREATEROLE NOCREATEDB NOREPLICATION NOINHERIT BYPASSRLS',
              HINT = 'DROP ROLE semantius_owner, or fix it with ALTER ROLE, then retry';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_catalog.pg_auth_members m
                WHERE m.roleid = r.oid) THEN
      RAISE EXCEPTION 'existing role semantius_owner already has members'
        USING ERRCODE = '55000',
              DETAIL = 'a member of semantius_owner would own every Semantius object after a restore',
              HINT = 'REVOKE semantius_owner FROM the listed roles, then retry';
    END IF;
  END IF;

  -- The other three may legitimately have LOGIN (pgdocker/init/10-roles.sql
  -- relies on it), but never superuser or BYPASSRLS.
  FOREACH r.rolname IN ARRAY ARRAY['authenticated', 'semantius_user', 'semantius_authenticator']
  LOOP
    SELECT * INTO r FROM pg_catalog.pg_roles WHERE rolname = r.rolname;
    IF FOUND AND (r.rolsuper OR r.rolbypassrls OR r.rolcreaterole
                  OR r.rolcreatedb OR r.rolreplication) THEN
      RAISE EXCEPTION 'existing role % has unexpected attributes', r.rolname
        USING ERRCODE = '55000',
              DETAIL = 'expected NOSUPERUSER NOBYPASSRLS NOCREATEROLE NOCREATEDB NOREPLICATION';
    END IF;
  END LOOP;

  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'semantius_user') THEN
    CREATE ROLE semantius_user INHERIT NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_auth_members m
                  JOIN pg_catalog.pg_roles g ON g.oid = m.roleid
                  JOIN pg_catalog.pg_roles n ON n.oid = m.member
                 WHERE g.rolname = 'semantius_user' AND n.rolname = 'authenticated') THEN
    GRANT semantius_user TO authenticated;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'semantius_authenticator') THEN
    CREATE ROLE semantius_authenticator NOLOGIN NOSUPERUSER NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_auth_members m
                  JOIN pg_catalog.pg_roles g ON g.oid = m.roleid
                  JOIN pg_catalog.pg_roles n ON n.oid = m.member
                 WHERE g.rolname = 'authenticated' AND n.rolname = 'semantius_authenticator') THEN
    GRANT authenticated TO semantius_authenticator WITH INHERIT FALSE, SET TRUE;
  END IF;
END
$pgsem_roles$;
${
    opts.upgrade ? "" : `
-- 3. The one schema this extension owns: a member, dropped with the extension.
--    NOT via the control file's \`schema\` parameter, which would create a
--    NON-member schema that survives DROP EXTENSION. No GRANT USAGE: only
--    superusers call these functions.
CREATE SCHEMA ${S};
COMMENT ON SCHEMA ${S} IS
  'Installer for the ${name} extension. Holds migrate()/pending()/version()/status(); no data.';
`
  }
${drops}
-- 4. The installer. Not SECURITY DEFINER: current_user, session_user and the
--    superuser check must be the CALLER's, which 0010, 0050 and 0290 rely on.
--    The SET clauses pin the settings the migrations assume, so a hostile or
--    merely unusual session cannot change what gets installed.
${orReplace} FUNCTION ${S}.migrate() RETURNS text
LANGUAGE plpgsql
SET search_path = public
SET standard_conforming_strings = on
SET check_function_bodies = on
AS ${OUTER_TAG}
DECLARE
  v_applied int := 0;
  v_skipped int := 0;
  v_start   timestamptz := clock_timestamp();
  v_state text; v_msg text; v_detail text; v_hint text; v_ctx text;
  v_bad   text;
BEGIN
  IF NOT (SELECT rolsuper FROM pg_catalog.pg_roles WHERE rolname = current_user) THEN
    RAISE EXCEPTION '${S}.migrate() must be run by a superuser (current_user is %)', current_user
      USING ERRCODE = '42501';
  END IF;

  -- A superuser session left in 'replica' would silently disable every
  -- dictionary trigger while the seed rows are written.
  PERFORM set_config('session_replication_role', 'origin', true);

  IF (SELECT pg_catalog.pg_encoding_to_char(encoding)
        FROM pg_catalog.pg_database WHERE datname = current_database()) <> 'UTF8' THEN
    RAISE EXCEPTION '${name} requires a UTF8 database' USING ERRCODE = '55000';
  END IF;

  -- The CLI runner's key (packages/cli/commands/migrate.ts), so two installers
  -- queue and an installer and the CLI conflict correctly.
  PERFORM pg_advisory_xact_lock(hashtext('migrate'));

  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pgmq') THEN
    RAISE EXCEPTION 'the pgmq extension is installed; ${name} vendors its own pgmq schema and would overwrite it'
      USING ERRCODE = '55000',
            HINT = 'DROP EXTENSION pgmq, or install into a different database';
  END IF;

  IF EXISTS (SELECT 1 FROM pg_extension e
               JOIN pg_namespace n ON n.oid = e.extnamespace
              WHERE e.extname = 'pgcrypto' AND n.nspname <> 'public') THEN
    RAISE EXCEPTION 'pgcrypto must be installed in schema public'
      USING ERRCODE = '55000',
            HINT = 'ALTER EXTENSION pgcrypto SET SCHEMA public';
  END IF;

  -- Refuse to run inside an extension script: everything created below would
  -- become a member of whatever extension is being created, which is exactly
  -- what this design exists to avoid.
  --
  -- The probe distinguishes the two cases by which error it raises. OUTSIDE a
  -- script pg_extension_config_dump() raises feature_not_supported (0A000).
  -- INSIDE one it gets far enough to complain that pg_class is not a member of
  -- the extension being created - a different, PostgreSQL-worded error. Catch
  -- both and decide from the flag, so the caller always sees this function's
  -- own message rather than a confusing one about pg_class.
  DECLARE
    v_in_extension_script boolean := true;
  BEGIN
    BEGIN
      PERFORM pg_catalog.pg_extension_config_dump('pg_catalog.pg_class'::regclass, '');
    EXCEPTION
      WHEN feature_not_supported THEN v_in_extension_script := false;
      WHEN OTHERS THEN v_in_extension_script := true;
    END;
    IF v_in_extension_script THEN
      RAISE EXCEPTION '${S}.migrate() cannot run inside a CREATE/ALTER EXTENSION script'
        USING ERRCODE = '55000',
              DETAIL = 'everything it creates would become a member of that extension',
              HINT = 'Run it as its own statement after CREATE EXTENSION';
    END IF;
  END;

  -- Same ledger the CLI runner uses, so either path recognises the other's work.
${
    getVersionsTableSql().split("\n").map((l) => (l ? "  " + l : l)).join("\n")
  }
${steps}
  -- Nothing the migrations created may belong to an extension.
  SELECT string_agg(DISTINCT e.extname, ', ') INTO v_bad
    FROM pg_depend d
    JOIN pg_extension e ON e.oid = d.refobjid
    JOIN pg_class c ON c.oid = d.objid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE d.refclassid = 'pg_extension'::regclass
     AND d.deptype = 'e'
     AND n.nspname IN (${CORE_SCHEMAS.map((x) => `'${x}'`).join(", ")})
     AND e.extname NOT IN (${
    MEMBERSHIP_ALLOWLIST.map((x) => `'${x}'`).join(", ")
  });
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION 'core objects became members of extension(s): %', v_bad
      USING ERRCODE = '55000',
            DETAIL = 'they would be dropped with that extension and skipped by pg_dump';
  END IF;

  NOTIFY pgrst, 'reload schema';

  RAISE NOTICE '${name}: % applied, % skipped in %',
    v_applied, v_skipped, clock_timestamp() - v_start;
  RETURN format('%s applied, %s skipped in %s',
                v_applied, v_skipped, clock_timestamp() - v_start);
END
${OUTER_TAG};

REVOKE EXECUTE ON FUNCTION ${S}.migrate() FROM PUBLIC;
COMMENT ON FUNCTION ${S}.migrate() IS
  'Applies the bundled core migrations as ordinary objects. Superuser only. Idempotent.';

-- 5. Read-only companions.
${orReplace} FUNCTION ${S}.pending() RETURNS SETOF text
LANGUAGE plpgsql STABLE
SET search_path = public
AS $pgsem_pending$
DECLARE
  v_all text[] := ARRAY[${names.map((n) => `'${escapeSqlLiteral(n)}'`).join(", ")}];
BEGIN
  -- Works before _versions exists (i.e. before the first migrate()).
  IF to_regclass('public._versions') IS NULL THEN
    RETURN QUERY SELECT unnest(v_all);
  ELSE
    RETURN QUERY SELECT x FROM unnest(v_all) AS x
      WHERE NOT EXISTS (SELECT 1 FROM public._versions v WHERE v.name = x);
  END IF;
END
$pgsem_pending$;
REVOKE EXECUTE ON FUNCTION ${S}.pending() FROM PUBLIC;
COMMENT ON FUNCTION ${S}.pending() IS
  'Bundled migrations not yet applied to this database.';

${orReplace} FUNCTION ${S}.version() RETURNS text
LANGUAGE sql STABLE
SET search_path = public
AS $pgsem_version$
  SELECT extversion FROM pg_extension WHERE extname = '${
    escapeSqlLiteral(name)
  }'
$pgsem_version$;
REVOKE EXECUTE ON FUNCTION ${S}.version() FROM PUBLIC;
COMMENT ON FUNCTION ${S}.version() IS
  'Version of the installed bundle (the installer, not the installed schema).';

${orReplace} FUNCTION ${S}.status()
RETURNS TABLE (
  extversion        text,
  db_version        text,
  applied           int,
  pending           int,
  unknown_versions  text[],
  changed_versions  text[],
  unowned_objects   int,
  default_acls_ok   boolean
)
LANGUAGE plpgsql STABLE
SET search_path = public
AS $pgsem_status$
DECLARE
  v_all text[] := ARRAY[${names.map((n) => `'${escapeSqlLiteral(n)}'`).join(", ")}];
  v_sums jsonb := '${
    JSON.stringify(
      Object.fromEntries(migs.map((m) => [`${m.app}.${m.name}`, m.checksum])),
    ).replace(/'/g, "''")
  }'::jsonb;
BEGIN
  extversion := ${S}.version();
  db_version := NULL;
  applied := 0; pending := 0;
  unknown_versions := ARRAY[]::text[];
  changed_versions := ARRAY[]::text[];

  IF to_regclass('public._settings') IS NOT NULL THEN
    BEGIN
      SELECT s.value INTO db_version FROM public._settings s WHERE s.key = 'db_version';
    EXCEPTION WHEN OTHERS THEN
      db_version := NULL;  -- shape differs or RLS denies: not fatal for status
    END;
  END IF;

  IF to_regclass('public._versions') IS NOT NULL THEN
    SELECT count(*)::int INTO applied
      FROM public._versions WHERE name = ANY(v_all);
    -- Rows this bundle does not know: a dump from a NEWER bundle restored onto
    -- an older installer.
    SELECT coalesce(array_agg(v.name ORDER BY v.name), ARRAY[]::text[])
      INTO unknown_versions
      FROM public._versions v
     WHERE v.name LIKE '%.%' AND NOT (v.name = ANY(v_all));
    -- Applied rows whose source text has changed since (Flyway's validate).
    SELECT coalesce(array_agg(v.name ORDER BY v.name), ARRAY[]::text[])
      INTO changed_versions
      FROM public._versions v
     WHERE v.name = ANY(v_all)
       AND v.checksum IS NOT NULL
       AND v.checksum IS DISTINCT FROM (v_sums ->> v.name);
  END IF;
  pending := array_length(v_all, 1) - applied;

  SELECT count(*)::int INTO unowned_objects
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname IN (${CORE_SCHEMAS.map((x) => `'${x}'`).join(", ")})
     AND c.relkind IN ('r', 'p', 'S', 'v')
     AND c.relowner <> COALESCE(
           (SELECT oid FROM pg_catalog.pg_roles WHERE rolname = 'semantius_owner'),
           c.relowner);

  -- The installer's ALTER DEFAULT PRIVILEGES bind to the INSTALLING role, so a
  -- restore by a differently named superuser loses them.
  default_acls_ok := EXISTS (
    SELECT 1 FROM pg_default_acl a
      JOIN pg_catalog.pg_roles r ON r.oid = a.defaclrole
     WHERE r.rolname = current_user);

  RETURN NEXT;
END
$pgsem_status$;
REVOKE EXECUTE ON FUNCTION ${S}.status() FROM PUBLIC;
COMMENT ON FUNCTION ${S}.status() IS
  'Install health: version drift, unknown or changed migrations, ownership and default-ACL drift after a restore.';
`;
}
