/**
 * Extension command implementation (CLI).
 *
 * Packages the core SQL migrations as a PostgreSQL extension — an *additional*
 * distribution channel for self-hosted PostgreSQL (see pgdocker/), alongside
 * the `migrate` deploy used for Neon/Supabase. It does not replace anything.
 *
 * It generates, into the output directory (default ./extension):
 *   - <name>.control            extension metadata (default_version, requires, ...)
 *   - <name>--<version>.sql      current full install (concatenated migrations)
 *   - <name>--<prev>--<version>.sql  upgrade script (migrations added since prev)
 *   - versions.json             manifest of each version's migration set + hashes
 *   - META.json                 PGXN distribution manifest
 *   - Makefile                  PGXS makefile so self-hosters can `make install`
 *   - README.md                 install instructions
 *
 * Versioning follows the pgTAP model: a single current full install plus an
 * accumulated chain of upgrade scripts (so `ALTER EXTENSION ... UPDATE` works).
 * Because the `_core` migrations are append-only ordered deltas, both are derived
 * automatically — the upgrade script is just the migrations added since the prior
 * version (per versions.json); editing a released migration is detected and warned.
 *
 * The transformation from migrations to SQL is intentionally small: the migration
 * files are already pure SQL executable as a single query (that is how
 * `executeMigrations` runs them), so we concatenate them in filename order and
 * only:
 *   - lift `CREATE EXTENSION ... <dep>` statements into the control `requires`
 *     list (you cannot nest CREATE EXTENSION inside an extension script), and
 *   - prepend the `_versions` tracking table and seed its run-once guard rows
 *     (the one piece of migrate-runner scaffolding the `_core` migrations
 *     actually depend on — `_core/0050` attaches an RLS policy to `_versions`,
 *     and seeding the rows lets a later `migrate` skip the already-applied
 *     `_core` migrations instead of re-running them), but add NO `NOTIFY pgrst`
 *     or BEGIN/COMMIT wrapping (CREATE EXTENSION runs in one transaction and
 *     pg_extension tracks the version).
 */

import { getVersionsTableSql } from "@semantius/core";

interface MigrationFile {
  name: string;
  content: string;
}

/**
 * PGXN-style version manifest. Records, per released version, the set of source
 * migrations it contained and their content hashes — so a later run can compute
 * the upgrade delta and detect edits to already-released migrations.
 */
interface VersionsManifest {
  versions: Record<string, { files: Record<string, string> }>;
}

interface ExtensionOptions {
  apps: string;
  version: string;
  name: string;
  outputDir: string;
}

export async function extensionCommand(
  options: ExtensionOptions,
): Promise<void> {
  const { version, name, outputDir } = options;
  const apps = !options.apps || options.apps.trim() === ""
    ? "_core"
    : options.apps;

  console.log(`Generating "${name}" extension v${version}...`);

  const appList = apps
    .split(",")
    .map((app) => app.trim())
    .filter((app) => app.length > 0);

  if (appList.length === 0) {
    console.error("No valid app names found");
    console.log("Provide comma-separated app names: app1,app2,app3");
    Deno.exit(1);
  }

  console.info(`Bundling app(s): ${appList.join(", ")}`);

  // Collect extension dependencies lifted out of the migration bodies.
  const requires = new Set<string>();

  const header = [
    `-- ${name} PostgreSQL extension`,
    `-- Version: ${version}`,
    `-- Generated by \`deno task extension\` from apps/{${
      appList.join(",")
    }}/migrations`,
    `-- DO NOT EDIT MANUALLY - regenerate after changing migrations.`,
    `--`,
    `-- Install:  CREATE EXTENSION ${name} CASCADE;`,
    ``,
    ``,
  ].join("\n");

  // Collect every migration (in filename order) with its raw + processed SQL.
  const migs: {
    app: string;
    name: string;
    content: string;
    processed: string;
  }[] = [];

  for (const app of appList) {
    const appPath = `./apps/${app}`;
    try {
      const stat = await Deno.stat(appPath);
      if (!stat.isDirectory) {
        console.warn(`Path exists but is not a directory, skipping: ${app}`);
        continue;
      }
    } catch (error) {
      if (error instanceof Deno.errors.NotFound) {
        console.warn(`App not found, skipping: ${app}`);
        continue;
      }
      throw error;
    }

    const migrationFiles = await loadSqlFiles(app, "migrations");

    if (migrationFiles.length === 0) {
      console.info(`No migration files found for ${app}`);
      continue;
    }

    console.info(`Found ${migrationFiles.length} migration file(s) for ${app}`);

    for (const migration of migrationFiles) {
      if (!migration.content.trim()) {
        console.warn(`  Warning: Migration file ${migration.name} is empty`);
        continue;
      }
      const processed = liftExtensionDependencies(
        migration.content,
        requires,
        name,
      );
      migs.push({
        app,
        name: migration.name,
        content: migration.content,
        processed,
      });
    }
  }

  const fullBody = renderBody(migs);

  if (fullBody.trim() === "") {
    console.error("No migration SQL was bundled; nothing to generate.");
    Deno.exit(1);
  }

  // Ensure output directory exists.
  await Deno.mkdir(outputDir, { recursive: true });

  // -- Versioning (pgTAP-style): one current full install + an accumulated
  //    chain of upgrade scripts, with a manifest tracking each version's
  //    migration set so deltas (and edits to released migrations) are detected.
  const manifestPath = `${outputDir}/versions.json`;
  const manifest = await loadManifest(manifestPath);

  const currentFiles: Record<string, string> = {};
  for (const m of migs) {
    currentFiles[`${m.app}/${m.name}`] = await sha256hex(m.content);
  }

  const prev = highestVersionBelow(version, manifest);
  if (prev) {
    const prevFiles = manifest.versions[prev].files;
    const added = migs.filter((m) => !(`${m.app}/${m.name}` in prevFiles));
    const edited = migs.filter((m) => {
      const k = `${m.app}/${m.name}`;
      return k in prevFiles && prevFiles[k] !== currentFiles[k];
    });
    const removed = Object.keys(prevFiles).filter((k) => !(k in currentFiles));

    if (edited.length > 0) {
      console.warn(
        `Warning: ${edited.length} migration(s) released in ${prev} were edited in place:`,
      );
      for (const m of edited) console.warn(`  - ${m.app}/${m.name}`);
      console.warn(
        `These edits are NOT captured by the ${prev} -> ${version} upgrade. Add a ` +
          `new migration for the change rather than editing a released one.`,
      );
    }
    if (removed.length > 0) {
      console.warn(
        `Warning: ${removed.length} migration(s) from ${prev} no longer exist; the ` +
          `upgrade script cannot undo them:`,
      );
      for (const k of removed) console.warn(`  - ${k}`);
    }

    const upgradeHeader = [
      `-- ${name} extension upgrade: ${prev} -> ${version}`,
      `-- Generated by \`deno task extension\` from migrations added since ${prev}.`,
      `-- DO NOT EDIT MANUALLY.`,
      ``,
      ``,
    ].join("\n");
    const upgradeBody = added.length > 0
      ? renderBody(added)
      : `-- No new migrations since ${prev}; version bump only.\n`;
    // `CREATE TABLE IF NOT EXISTS _versions` for idempotent safety (it already
    // exists from the original install), then seed only the delta migrations'
    // run-once guards so `_versions` stays consistent across ALTER EXTENSION
    // ... UPDATE.
    await Deno.writeTextFile(
      `${outputDir}/${name}--${prev}--${version}.sql`,
      upgradeHeader + renderVersionsTable() + upgradeBody +
        renderVersionsSeed(added),
    );
    console.info(
      `Wrote upgrade ${name}--${prev}--${version}.sql (${added.length} migration(s))`,
    );
  }

  // Record this version's migration set, then drop superseded full installs
  // (keep the current full install + the whole upgrade chain).
  manifest.versions[version] = { files: currentFiles };
  await Deno.writeTextFile(manifestPath, serializeManifest(manifest));
  const pruned = await pruneOldFullInstalls(outputDir, name, version);

  const controlPath = `${outputDir}/${name}.control`;
  const sqlPath = `${outputDir}/${name}--${version}.sql`;
  const makefilePath = `${outputDir}/Makefile`;
  const readmePath = `${outputDir}/README.md`;
  const metaPath = `${outputDir}/META.json`;

  await Deno.writeTextFile(
    controlPath,
    buildControlFile(name, version, requires),
  );
  // Full install = header + _versions table (so _core/0050's RLS policy can
  // attach) + migration bodies + seeded run-once guards (so a later `migrate`
  // skips the already-applied migrations).
  const installSql = header + renderVersionsTable() + fullBody +
    renderVersionsSeed(migs);
  await Deno.writeTextFile(sqlPath, installSql);
  await Deno.writeTextFile(makefilePath, buildMakefile(name));
  await Deno.writeTextFile(readmePath, buildReadme(name, version, requires));
  // META.json is the PGXN distribution manifest (https://pgxn.org/meta/spec.txt).
  await Deno.writeTextFile(metaPath, buildMetaJson(name, version, requires));

  const sqlBytes = new TextEncoder().encode(installSql).length;

  console.log("");
  console.log(`Extension generated in ${outputDir}/ (version ${version}):`);
  console.log(`  ${name}.control`);
  console.log(
    `  ${name}--${version}.sql  (${formatBytes(sqlBytes)})  [full install]`,
  );
  if (prev) console.log(`  ${name}--${prev}--${version}.sql  [upgrade]`);
  console.log(
    `  versions.json  (${Object.keys(manifest.versions).length} version(s))`,
  );
  console.log(`  Makefile, META.json, README.md`);
  for (const f of pruned) {
    console.log(`  (removed superseded full install ${f})`);
  }
  if (requires.size > 0) {
    console.log(`  requires: ${[...requires].sort().join(", ")}`);
  }
  console.log("");
  if (prev) {
    console.log(`Fresh install:  CREATE EXTENSION ${name} CASCADE;`);
    console.log(
      `Upgrade:        ALTER EXTENSION ${name} UPDATE TO '${version}';`,
    );
  } else {
    console.log(
      `Install:  make install  &&  CREATE EXTENSION ${name} CASCADE;`,
    );
  }
  console.log("Extension generation completed!");
}

/** Renders migrations into a SQL body with a banner before each. */
function renderBody(
  migs: { app: string; name: string; processed: string }[],
): string {
  let body = "";
  for (const m of migs) {
    body += `-- =====================================================\n`;
    body += `-- ${m.app}/${m.name}\n`;
    body += `-- =====================================================\n`;
    body += m.processed;
    if (!m.processed.endsWith("\n")) body += "\n";
    body += "\n";
  }
  return body;
}

/**
 * The `_versions` tracking table section, emitted at the TOP of the script
 * (before the migration bodies). The migrate runner creates this table via
 * `ensureVersionsTable()` before any migration runs; `CREATE EXTENSION` has no
 * such step, so the extension must emit it itself — otherwise `_core/0050`'s
 * `CREATE POLICY ... ON _versions` has no table to attach to and the whole
 * install fails ("relation _versions does not exist").
 *
 * Uses the shared `getVersionsTableSql()` (CREATE TABLE IF NOT EXISTS + unique
 * index + ENABLE RLS) verbatim, so the table is byte-identical to a migrate
 * deploy. It is intentionally unqualified: the bare `CREATE TABLE _versions`
 * lands in `public` because the installing superuser's search_path resolves
 * there (relocatable = false, no schema param) — the same assumption the rest of
 * the generated script already relies on (`_settings`, the RBAC tables, ... are
 * all created unqualified too). The RLS policy is NOT created here; `_core/0050`
 * owns it (re-creating it would error).
 */
function renderVersionsTable(): string {
  return `-- =====================================================
-- _versions tracking table (run-once migration guard)
-- =====================================================
-- Created before the migration bodies so _core/0050's
-- \`CREATE POLICY ... ON _versions\` can attach. The migrate
-- runner creates this via ensureVersionsTable(); CREATE
-- EXTENSION must emit it itself.
${getVersionsTableSql()}

`;
}

/**
 * Seeds the run-once guard rows into `_versions` — one row per bundled
 * migration, named exactly as the migrate runner records them (`${app}.${name}`,
 * matching migrate.ts) — so a later `deno task migrate` against an
 * extension-installed database finds every bundled migration already recorded
 * and SKIPS re-running it. Re-running `_core` is unsafe (e.g. 0010's bare
 * `CREATE TABLE _settings` has no IF NOT EXISTS and would error), so this is what
 * makes the extension-installed DB safely CLI-manageable.
 *
 * Qualified `public._versions` to match the migrate runner's own write
 * (migrate.ts). `ON CONFLICT DO NOTHING` keeps it idempotent. Names are derived
 * from the collected migrations, never hand-typed, so they cannot drift from
 * what `migrate` computes. Emits nothing for an empty set (version-bump-only
 * upgrades).
 */
function renderVersionsSeed(
  migs: { app: string; name: string }[],
): string {
  if (migs.length === 0) return "";
  const values = migs
    .map((m) => `  ('${escapeSqlLiteral(`${m.app}.${m.name}`)}')`)
    .join(",\n");
  return `-- =====================================================
-- Seed _versions run-once guards (one row per migration)
-- =====================================================
-- So a subsequent \`deno task migrate\` skips these
-- already-applied migrations instead of re-running them.
INSERT INTO public._versions (name) VALUES
${values}
ON CONFLICT DO NOTHING;

`;
}

/** Escapes single quotes for safe embedding in a SQL string literal. */
function escapeSqlLiteral(text: string): string {
  return text.replace(/'/g, "''");
}

/** SHA-256 hex digest of a string (used to fingerprint migration sources). */
async function sha256hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text),
  );
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/** Compares dotted numeric versions (e.g. "0.2.0" vs "0.10.0"). */
function compareVersions(a: string, b: string): number {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const da = pa[i] ?? 0;
    const db = pb[i] ?? 0;
    if (da !== db) return da - db;
  }
  return 0;
}

/** Highest manifest version strictly below `target`, or undefined if none. */
function highestVersionBelow(
  target: string,
  manifest: VersionsManifest,
): string | undefined {
  const prior = Object.keys(manifest.versions)
    .filter((v) => compareVersions(v, target) < 0)
    .sort(compareVersions);
  return prior[prior.length - 1];
}

/** Loads the version manifest, returning an empty one if absent. */
async function loadManifest(path: string): Promise<VersionsManifest> {
  try {
    const parsed = JSON.parse(await Deno.readTextFile(path));
    return parsed && typeof parsed === "object" && parsed.versions
      ? parsed as VersionsManifest
      : { versions: {} };
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return { versions: {} };
    throw error;
  }
}

/** Serializes the manifest with versions and file keys sorted, for stable diffs. */
function serializeManifest(manifest: VersionsManifest): string {
  const versions: VersionsManifest["versions"] = {};
  for (const v of Object.keys(manifest.versions).sort(compareVersions)) {
    const files: Record<string, string> = {};
    for (const k of Object.keys(manifest.versions[v].files).sort()) {
      files[k] = manifest.versions[v].files[k];
    }
    versions[v] = { files };
  }
  return JSON.stringify({ versions }, null, 2) + "\n";
}

/**
 * Removes superseded full-install scripts (`<name>--<version>.sql`) from the
 * output dir, keeping only `keepVersion`. Upgrade scripts (`<name>--<a>--<b>.sql`,
 * which contain a second `--`) are left untouched. Returns the removed filenames.
 */
async function pruneOldFullInstalls(
  dir: string,
  name: string,
  keepVersion: string,
): Promise<string[]> {
  const prefix = `${name}--`;
  const removed: string[] = [];
  for await (const entry of Deno.readDir(dir)) {
    if (!entry.isFile) continue;
    if (!entry.name.startsWith(prefix) || !entry.name.endsWith(".sql")) {
      continue;
    }
    const mid = entry.name.slice(prefix.length, -".sql".length);
    if (mid.includes("--")) continue; // upgrade script — keep
    if (mid !== keepVersion) {
      await Deno.remove(`${dir}/${entry.name}`);
      removed.push(entry.name);
    }
  }
  return removed;
}

/**
 * Rewrites `CREATE EXTENSION [IF NOT EXISTS] <dep> ...;` statements out of the
 * SQL body and records <dep> in the requires set. Nested CREATE EXTENSION is not
 * permitted inside an extension script; dependencies belong in the control file.
 * Only single-line statements (the form used in this codebase) are matched.
 */
function liftExtensionDependencies(
  content: string,
  requires: Set<string>,
  name: string,
): string {
  const lines = content.split("\n");
  const out: string[] = [];

  for (const line of lines) {
    const trimmed = line.trimStart();
    // Skip comment lines so a commented-out CREATE EXTENSION is left untouched.
    if (!trimmed.startsWith("--")) {
      const match = trimmed.match(
        /^CREATE\s+EXTENSION\s+(?:IF\s+NOT\s+EXISTS\s+)?["']?([A-Za-z0-9_]+)["']?[^;]*;?\s*$/i,
      );
      if (match) {
        requires.add(match[1].toLowerCase());
        out.push(
          `-- [extension] dependency declared in ${name}.control \`requires\`: ${trimmed}`,
        );
        continue;
      }
    }
    out.push(line);
  }

  return out.join("\n");
}

/** Builds the .control file contents. */
function buildControlFile(
  name: string,
  version: string,
  requires: Set<string>,
): string {
  const lines = [
    `# ${name} extension control file`,
    `# Generated by \`deno task extension\` - do not edit manually.`,
    `comment = 'Semantius core: RBAC, RLS, data dictionary, and message queue'`,
    `default_version = '${version}'`,
    // Multi-schema (public, common, rbac, audit, pgmq) so it cannot be relocated.
    `relocatable = false`,
    // The script creates roles, event triggers and ALTER DEFAULT PRIVILEGES,
    // all of which require a superuser to install.
    `superuser = true`,
  ];

  if (requires.size > 0) {
    lines.push(`requires = '${[...requires].sort().join(", ")}'`);
  }

  return lines.join("\n") + "\n";
}

/** Builds a PGXS Makefile that installs every generated version script. */
function buildMakefile(name: string): string {
  return [
    `# Generated by \`deno task extension\` - do not edit manually.`,
    `# Installs the ${name} extension into PostgreSQL's extension directory.`,
    `#   make install   (uses pg_config; may need sudo)`,
    ``,
    `EXTENSION = ${name}`,
    `DATA = $(wildcard ${name}--*.sql)`,
    ``,
    `PG_CONFIG ?= pg_config`,
    `PGXS := $(shell $(PG_CONFIG) --pgxs)`,
    `include $(PGXS)`,
    ``,
  ].join("\n");
}

/**
 * Builds the PGXN distribution manifest (META.json, Meta Spec 1.0.0) so the
 * extension can be published to and installed from PGXN (`pgxn install pg_semantius`).
 * Version is kept in sync with the generated SQL on every run.
 */
function buildMetaJson(
  name: string,
  version: string,
  requires: Set<string>,
): string {
  const prereqRequires: Record<string, string> = { PostgreSQL: "18.0.0" };

  const meta = {
    name,
    abstract:
      "Database-first RBAC, RLS, data dictionary, and message queue for PostgreSQL",
    description:
      "Semantius core packaged as a PostgreSQL extension: role-based access " +
      "control, row-level security, a semantic data dictionary, and a message " +
      "queue. An alternative to deploying the migrations with the Semantius CLI.",
    version,
    maintainer: ["adenin TECHNOLOGIES"],
    license: "mit",
    provides: {
      [name]: {
        abstract:
          "Semantius core: RBAC, RLS, data dictionary, and message queue",
        file: `${name}--${version}.sql`,
        docfile: "README.md",
        version,
      },
    },
    prereqs: {
      runtime: {
        requires: prereqRequires,
      },
    },
    resources: {
      homepage: "https://github.com/semantius/semantius",
      bugtracker: {
        web: "https://github.com/semantius/semantius/issues",
      },
      repository: {
        url: "git://github.com/semantius/semantius.git",
        web: "https://github.com/semantius/semantius",
        type: "git",
      },
    },
    generated_by: "deno task extension",
    "meta-spec": {
      version: "1.0.0",
      url: "https://pgxn.org/meta/spec.txt",
    },
    tags: [
      "rbac",
      "rls",
      "row level security",
      "data dictionary",
      "queue",
      "security",
    ],
  };

  // Record extension dependencies (e.g. pgcrypto) as runtime prereqs too.
  for (const dep of [...requires].sort()) {
    prereqRequires[dep] = "0";
  }

  return JSON.stringify(meta, null, 2) + "\n";
}

/** Builds the README with install instructions. */
function buildReadme(
  name: string,
  version: string,
  requires: Set<string>,
): string {
  const reqList = requires.size > 0
    ? [...requires].sort().join(", ")
    : "(none)";
  return `# ${name} PostgreSQL extension

Generated by \`deno task extension\` from \`apps/_core/migrations\`.
**Do not edit by hand** - regenerate after changing migrations.

This packages Semantius core (RBAC, RLS, data dictionary, message queue) as a
PostgreSQL extension. It is an **additional** distribution channel for
self-hosted PostgreSQL 18 (see \`../pgdocker\`), alongside the \`deno task migrate\`
deploy used for Neon/Supabase. It replaces nothing.

Current version: \`${version}\`
Requires: ${reqList}

## Install

Requires **PostgreSQL 18** and a **superuser** connection (the extension creates
roles and event triggers). \`CASCADE\` auto-installs the required extensions
(${reqList}); the extension creates its own \`authenticated\` and \`semantius_user\`
roles, so on a vanilla server there is nothing to set up first.

**From PGXN:**

\`\`\`sh
pgxn install ${name}
\`\`\`

**From a release download (or this folder):**

\`\`\`sh
make install            # uses pg_config to find $(SHAREDIR)/extension; may need sudo
# or copy the files manually:
cp ${name}.control ${name}--*.sql "$(pg_config --sharedir)/extension/"
\`\`\`

**Then, in the target database:**

\`\`\`sql
CREATE EXTENSION ${name} CASCADE;        -- fresh install of the current version
\`\`\`

**Upgrade** an existing install to a newer version (walks the bundled
\`${name}--<old>--<new>.sql\` chain):

\`\`\`sql
ALTER EXTENSION ${name} UPDATE;          -- or UPDATE TO '<version>'
\`\`\`

## Build a new version

Run from the repo root. Writes the current full install \`${name}--<version>.sql\`,
an upgrade script \`${name}--<prev>--<version>.sql\` containing the migrations added
since the previous version, bumps \`default_version\` in \`${name}.control\`, records
the version in \`versions.json\`, and refreshes \`META.json\`/\`Makefile\`/README:

\`\`\`sh
deno task extension <version>          # e.g. deno task extension 0.2.0
\`\`\`

Once a version is released its migrations are **frozen** — make later changes in
*new* migration files, not by editing released ones (the generator warns if a
released migration's content changed, since that edit can't land in an upgrade
script).

## Caveat

Every table the install script creates becomes a member of the extension, so
\`DROP EXTENSION ${name}\` will drop the data-dictionary tables **and their
contents**. Back up first. (A follow-up can mark seed/config tables with
\`pg_extension_config_dump()\` so \`pg_dump\` captures their rows.)
`;
}

/** Loads all .sql files from apps/{folderName}/{subfolder}/ sorted ascending. */
async function loadSqlFiles(
  folderName: string,
  subfolder: string,
): Promise<MigrationFile[]> {
  const sqlPath = `./apps/${folderName}/${subfolder}`;

  try {
    const sqlFileNames: string[] = [];

    for await (const dirEntry of Deno.readDir(sqlPath)) {
      if (dirEntry.isFile && dirEntry.name.endsWith(".sql")) {
        sqlFileNames.push(dirEntry.name);
      }
    }

    sqlFileNames.sort();

    const migrations: MigrationFile[] = [];
    for (const fileName of sqlFileNames) {
      const filePath = `${sqlPath}/${fileName}`;
      const content = await Deno.readTextFile(filePath);
      migrations.push({
        name: fileName.replace(/\.sql$/, ""),
        content,
      });
    }

    return migrations;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      console.info(`No ${subfolder} folder found at: ${sqlPath}`);
      return [];
    }
    console.error(
      `Error reading ${subfolder} folder ${sqlPath}:`,
      error instanceof Error ? error.message : String(error),
    );
    return [];
  }
}

/** Human-readable byte size. */
function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
