/**
 * testgen_jsonlogic command
 * Generates 0015_test_jsonlogic.sql from 0015_test_jsonlogic.json
 *
 * JSON format:
 *   - String entries are converted to SQL comments
 *   - Array entries [rule, data, result] produce a pgTAP is() assertion that
 *     calls evaluate_json_logic(rule::jsonb, data::jsonb) and compares the
 *     result to the expected value.
 */

const JSON_INPUT_PATH = "./apps/test/tests/0015_test_jsonlogic.json";
const SQL_OUTPUT_PATH = "./apps/test/tests/0015_test_jsonlogic.sql";

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

function toJsonbLiteral(value: unknown): string {
  return `'${sqlEscape(JSON.stringify(value))}'::jsonb`;
}

export async function testgenJsonlogicCommand(): Promise<void> {
  console.log(`Reading ${JSON_INPUT_PATH}...`);

  let entries: unknown[];
  try {
    const content = await Deno.readTextFile(JSON_INPUT_PATH);
    const parsed = JSON.parse(content);
    if (!Array.isArray(parsed)) {
      console.error(`Expected ${JSON_INPUT_PATH} to contain a JSON array`);
      Deno.exit(1);
    }
    entries = parsed;
  } catch (error) {
    console.error(
      `Failed to read ${JSON_INPUT_PATH}:`,
      error instanceof Error ? error.message : String(error),
    );
    Deno.exit(1);
  }

  const testCount = entries.filter((e) => Array.isArray(e) && (e as unknown[]).length >= 3).length;

  const lines: string[] = [];
  lines.push(
    "-- Generated by testgen_jsonlogic command",
  );
  lines.push(
    "-- DO NOT EDIT - modify 0015_test_jsonlogic.json and run deno task testgen_jsonlogic",
  );
  lines.push("BEGIN;");
  lines.push("");
  lines.push(`SELECT plan(${testCount});`);
  lines.push("");

  let testNum = 0;

  for (const entry of entries) {
    if (typeof entry === "string") {
      lines.push(`-- ${entry}`);
    } else if (Array.isArray(entry)) {
      if (entry.length < 3) {
        console.warn(
          `Skipping malformed test entry (expected [rule, data, result], got ${entry.length} element(s)): ${JSON.stringify(entry)}`,
        );
        continue;
      }
      const [rule, data, result] = entry;
      testNum++;
      lines.push(`SELECT is(`);
      lines.push(
        `    evaluate_json_logic(${toJsonbLiteral(rule)}, ${toJsonbLiteral(data)}),`,
      );
      lines.push(`    ${toJsonbLiteral(result)},`);
      lines.push(`    'test ${testNum}'`);
      lines.push(`);`);
    }
  }

  lines.push("");
  lines.push("SELECT * FROM finish();");
  lines.push("ROLLBACK;");

  const sql = lines.join("\n");

  await Deno.writeTextFile(SQL_OUTPUT_PATH, sql);
  console.log(`Generated ${SQL_OUTPUT_PATH} with ${testCount} tests.`);
}
