#!/bin/sh
# Runs on the HOST before the devcontainer is created (devcontainer.json ->
# initializeCommand), including in GitHub Codespaces. It decides whether the
# bundled local Postgres (the compose `localdb` profile) should run, based on
# whether a managed DATABASE_URL is provided (env var or Codespaces secret).
#
# It writes COMPOSE_PROFILES (and DATABASE_URL, so compose interpolation is
# reliable) into .devcontainer/.env, which docker compose reads for this project.
#   - DATABASE_URL set  -> COMPOSE_PROFILES=        (local Postgres NOT started)
#   - DATABASE_URL unset -> COMPOSE_PROFILES=localdb (local Postgres started)
set -eu
env_file="$(dirname "$0")/.env"

if [ -n "${DATABASE_URL:-}" ]; then
  {
    echo "# generated by select-db.sh — do not commit"
    echo "DATABASE_URL=$DATABASE_URL"
    echo "COMPOSE_PROFILES="
  } > "$env_file"
  echo "[devcontainer] DATABASE_URL is set -> using the managed database; local Postgres disabled."
else
  {
    echo "# generated by select-db.sh — do not commit"
    echo "COMPOSE_PROFILES=localdb"
  } > "$env_file"
  echo "[devcontainer] no DATABASE_URL -> starting the local Postgres (pgdocker)."
fi
