/**
 * @semantius/neon-provisioner - Migrate function
 *
 * Executes Semantius database migrations from within a Cloudflare Worker.
 * Uses pre-bundled SQL content (generated by `deno task bundle-sql`) instead
 * of reading from the filesystem, making it suitable for Cloudflare Workers.
 *
 * Uses @neondatabase/serverless as the PostgreSQL client, which is compatible
 * with Cloudflare Workers via WebSocket connections.
 *
 * The migration logic itself is shared with @semantius/triggerdev through
 * the @semantius/core package (runMigrations), including the run rules.
 */

import { Pool } from "@neondatabase/serverless";
import { type AppMigrations, runMigrations } from "@semantius/core";
import { getBundledMigrations } from "./migrations-bundle.js";

export interface MigrateOptions {
  /** If true, enables verbose logging. Defaults to false. */
  verbose?: boolean;
}

export interface MigrateResult {
  success: boolean;
  message: string;
  modules: string[];
}

/**
 * Runs database migrations for the specified modules using bundled SQL content.
 *
 * @param databaseUrl  PostgreSQL connection URL (e.g. postgresql://user:pass@host/db)
 * @param modules      List of module/app names to migrate.
 *                     Defaults to "_core" alone: a sample module such as
 *                     nwind is bundled too, and must be asked for by name.
 *                     The "_core" module is always prepended automatically.
 * @param options      Optional configuration (verbose logging, etc.)
 */
export async function migrate(
  databaseUrl: string,
  modules?: string[],
  options: MigrateOptions = {},
): Promise<MigrateResult> {
  const { verbose = false } = options;

  const log = (msg: string) => console.log(`[semantius/neon-provisioner] ${msg}`);
  const logVerbose = (msg: string) => {
    if (verbose) log(msg);
  };

  log("Starting migration...");

  // Determine which apps to migrate
  let appsToMigrate: string[];
  if (!modules || modules.length === 0) {
    appsToMigrate = ["_core"];
    logVerbose("No modules specified - migrating _core only");
  } else {
    // Always ensure _core is first
    const withoutCore = modules.filter((m) => m !== "_core");
    appsToMigrate = ["_core", ...withoutCore];
    logVerbose(`Modules to migrate: ${appsToMigrate.join(", ")}`);
  }

  // Use neon's WebSocket-based Pool - supports multi-statement queries.
  // ONE client for the whole pass: pool.query() may hand every query to a
  // different pooled connection, so BEGIN / file / COMMIT would not be one
  // transaction and the session lock would be held by some other connection.
  const pool = new Pool({ connectionString: databaseUrl });
  const client = await pool.connect();

  // Wrap the client to match the DatabaseClient interface expected by core
  const dbClient = {
    queryObject: async (
      query: string,
      params?: unknown[],
    ): Promise<{ rows: Record<string, unknown>[] }> => {
      const result = params && params.length > 0
        ? await client.query(query, params as unknown[])
        : await client.query(query);
      return { rows: result.rows as Record<string, unknown>[] };
    },
  };

  const apps: AppMigrations[] = [];
  for (const appName of appsToMigrate) {
    const migrations = getBundledMigrations(appName);
    if (migrations.length === 0) {
      log(`No bundled migrations found for app: ${appName} - skipping`);
      continue;
    }
    log(`Migrating app: ${appName} (${migrations.length} file(s))`);
    apps.push({ app: appName, migrations });
  }

  try {
    const result = await runMigrations(dbClient, apps);
    log(
      `All migrations completed successfully (${result.applied} applied, ${result.skipped} skipped).`,
    );
  } finally {
    client.release();
    await pool.end();
  }

  return {
    success: true,
    message: "All migrations completed successfully.",
    modules: appsToMigrate,
  };
}

export { getBundledAppNames, getBundledMigrations } from "./migrations-bundle.js";
export type { MigrationFile } from "@semantius/core";
