/**
 * @semantius/neon-provisioner - Migrate function
 *
 * Executes Semantius database migrations from within a Cloudflare Worker.
 * Uses pre-bundled SQL content (generated by `deno task bundle-sql`) instead
 * of reading from the filesystem, making it suitable for Cloudflare Workers.
 *
 * Uses @neondatabase/serverless as the PostgreSQL client, which is compatible
 * with Cloudflare Workers via WebSocket connections.
 *
 * The migration logic itself is shared with @semantius/triggerdev through
 * the @semantius/core package (ensureVersionsTable, executeMigrations).
 */

import { Pool } from "@neondatabase/serverless";
import {
  ensureVersionsTable,
  executeMigrations,
  type MigrationFile,
} from "@semantius/core";
import {
  getBundledAppNames,
  getBundledMigrations,
} from "./migrations-bundle.js";

export interface MigrateOptions {
  /** If true, enables verbose logging. Defaults to false. */
  verbose?: boolean;
}

export interface MigrateResult {
  success: boolean;
  message: string;
  modules: string[];
}

/**
 * Runs database migrations for the specified modules using bundled SQL content.
 *
 * @param databaseUrl  PostgreSQL connection URL (e.g. postgresql://user:pass@host/db)
 * @param modules      List of module/app names to migrate.
 *                     Defaults to all bundled apps if not provided.
 *                     The "_core" module is always prepended automatically.
 * @param options      Optional configuration (verbose logging, etc.)
 */
export async function migrate(
  databaseUrl: string,
  modules?: string[],
  options: MigrateOptions = {},
): Promise<MigrateResult> {
  const { verbose = false } = options;

  const log = (msg: string) => console.log(`[semantius/neon-provisioner] ${msg}`);
  const logVerbose = (msg: string) => {
    if (verbose) log(msg);
  };

  log("Starting migration...");

  // Determine which apps to migrate
  let appsToMigrate: string[];
  if (!modules || modules.length === 0) {
    appsToMigrate = getBundledAppNames();
    logVerbose(
      `No modules specified - using all bundled apps: ${appsToMigrate.join(", ")}`,
    );
  } else {
    // Always ensure _core is first
    const withoutCore = modules.filter((m) => m !== "_core");
    appsToMigrate = ["_core", ...withoutCore];
    logVerbose(`Modules to migrate: ${appsToMigrate.join(", ")}`);
  }

  // Use neon's WebSocket-based Pool - supports multi-statement queries
  const pool = new Pool({ connectionString: databaseUrl });

  // Wrap pool client to match the DatabaseClient interface expected by core
  const dbClient = {
    queryObject: async (
      query: string,
      params?: unknown[],
    ): Promise<{ rows: Record<string, unknown>[] }> => {
      const result = params && params.length > 0
        ? await pool.query(query, params as unknown[])
        : await pool.query(query);
      return { rows: result.rows as Record<string, unknown>[] };
    },
  };

  // Acquire advisory lock to prevent concurrent migrations
  const lockResult = await dbClient.queryObject(
    "SELECT pg_try_advisory_lock(hashtext('migrate')) AS acquired",
  );
  const lockAcquired = (lockResult.rows[0] as { acquired: boolean }).acquired;

  if (!lockAcquired) {
    throw new Error(
      "Failed to acquire migration lock. Another migration may already be running.",
    );
  }

  logVerbose("Migration lock acquired");

  try {
    for (const appName of appsToMigrate) {
      const migrations: MigrationFile[] = getBundledMigrations(appName);

      if (migrations.length === 0) {
        log(`No bundled migrations found for app: ${appName} - skipping`);
        continue;
      }

      log(`Migrating app: ${appName} (${migrations.length} file(s))`);
      await ensureVersionsTable(dbClient);
      await executeMigrations(appName, migrations, dbClient);
      log(`Completed: ${appName}`);
    }

    log("All migrations completed successfully.");
  } finally {
    try {
      await dbClient.queryObject(
        "SELECT pg_advisory_unlock(hashtext('migrate'))",
      );
      logVerbose("Migration lock released");
    } catch (unlockError) {
      console.error(
        "[semantius/neon-provisioner] Warning: failed to release migration lock:",
        unlockError instanceof Error
          ? unlockError.message
          : String(unlockError),
      );
    }
    await pool.end();
  }

  return {
    success: true,
    message: "All migrations completed successfully.",
    modules: appsToMigrate,
  };
}

export { getBundledAppNames, getBundledMigrations } from "./migrations-bundle.js";
export type { MigrationFile } from "@semantius/core";
