// AUTO-GENERATED by `deno task kyselygen`. Do not edit by hand.

export type * from "./admin";

import type {
  AuditDdlLogs,
  AuditRecordLogs,
  Entities,
  Fields,
  Modules,
  PermissionHierarchy,
  Permissions,
  ProcessGates,
  Processes,
  QueueTableEvents,
  Queues,
  RaciAssignments,
  RaciEvents,
  RolePermissions,
  Roles,
  UserPermissions,
  UserRoles,
  Users,
} from "./admin";

export interface DB {
  audit_ddl_logs: AuditDdlLogs;
  audit_record_logs: AuditRecordLogs;
  entities: Entities;
  fields: Fields;
  modules: Modules;
  permission_hierarchy: PermissionHierarchy;
  permissions: Permissions;
  process_gates: ProcessGates;
  processes: Processes;
  queue_table_events: QueueTableEvents;
  queues: Queues;
  raci_assignments: RaciAssignments;
  raci_events: RaciEvents;
  role_permissions: RolePermissions;
  roles: Roles;
  user_permissions: UserPermissions;
  user_roles: UserRoles;
  users: Users;
}
