#!/usr/bin/env bun
// Extracts every `CREATE OR REPLACE FUNCTION ... $$ LANGUAGE ...;` statement
// from the listed migration files and concatenates them into rename.sql.
//
// Parser: locate `CREATE OR REPLACE FUNCTION`, then the opening `$$`, then the
// matching closing `$$`, then the terminating `;`. Nested DECLARE/BEGIN/END
// blocks are safe because they live entirely inside the dollar-quoted body.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const MIGRATIONS_DIR = resolve(import.meta.dir, "..", "apps", "_core", "migrations");
const SOURCES = [
  "0070_dd_functions.sql",
  "0140_dd_rename.sql",
  "0145_managed_enable.sql",
];
const OUTPUT = resolve(import.meta.dir, "..", "rename.sql");

const HEAD = "CREATE OR REPLACE FUNCTION";

function extract(sql: string): string[] {
  const blocks: string[] = [];
  let i = 0;
  while (true) {
    const start = sql.indexOf(HEAD, i);
    if (start < 0) break;
    const openDollar = sql.indexOf("$$", start);
    if (openDollar < 0) throw new Error(`No opening $$ after CREATE at ${start}`);
    const closeDollar = sql.indexOf("$$", openDollar + 2);
    if (closeDollar < 0) throw new Error(`No closing $$ after open at ${openDollar}`);
    const semi = sql.indexOf(";", closeDollar + 2);
    if (semi < 0) throw new Error(`No ; after closing $$ at ${closeDollar}`);
    blocks.push(sql.slice(start, semi + 1));
    i = semi + 1;
  }
  return blocks;
}

const out: string[] = [
  "-- =====================================================",
  "-- Generated by scripts/extract-functions.ts",
  "-- All CREATE OR REPLACE FUNCTION statements from:",
  ...SOURCES.map((s) => `--   ${s}`),
  "-- =====================================================",
  "",
];

let total = 0;
for (const file of SOURCES) {
  const path = resolve(MIGRATIONS_DIR, file);
  const sql = readFileSync(path, "utf8");
  const blocks = extract(sql);
  total += blocks.length;
  out.push(`-- --- from ${file} (${blocks.length} functions) ---`, "");
  for (const block of blocks) {
    const nameMatch = block.match(/CREATE OR REPLACE FUNCTION\s+([^\s(]+)/);
    out.push(`-- ${nameMatch?.[1] ?? "?"}`);
    out.push(block, "");
  }
}

writeFileSync(OUTPUT, out.join("\n"));
console.log(`Wrote ${total} functions to ${OUTPUT}`);
