-- A non-admin cannot write the users table or the RBAC tables.
--
-- Each part sets up its own fixtures; a part after the first starts by
-- restoring the connection's role and the runner's search_path. Parts:
--   1. users table write protection
--   2. No escalation through the RBAC tables
BEGIN;

SELECT plan(9);

-- =====================================================
-- PART 1: users table write protection
-- =====================================================
-- Verify that a regular (non-admin) user cannot write the users table directly.
--
-- Only admins (the `user:manage` permission) may INSERT/UPDATE/DELETE users via
-- RLS (the policies create_entity_policies in 0160_dd_functions.sql generates
-- from users.edit_permission). First-login provisioning happens through the
-- SECURITY DEFINER rbac.upsert_user_from_jwt(), which bypasses RLS but only ever
-- touches the caller's OWN row. A regular user must NOT be able to change any
-- user row (their own or someone else's) by writing the table directly.

-- user1 is a regular user (no user:manage).
SELECT authenticate_as('user1');

-- 1. INSERT is rejected by the RLS WITH CHECK (insufficient_privilege).
SELECT throws_ok(
    $$ INSERT INTO users (external_id, email) VALUES ('attacker_injected', 'evil@example.com') $$,
    '42501',
    NULL,
    'regular user cannot INSERT into users (RLS WITH CHECK)'
);

-- 2. UPDATE of another user's email is a silent no-op: RLS USING hides the row,
--    so zero rows are affected (and nothing changes).
WITH upd AS (
    UPDATE users SET email = 'hacked@evil.com' WHERE external_id = 'user2' RETURNING 1
)
SELECT is( count(*)::int, 0,
    'regular user UPDATE of another user affects 0 rows' ) FROM upd;

-- 3. DELETE is likewise a no-op for a regular user.
WITH del AS (
    DELETE FROM users WHERE external_id = 'user2' RETURNING 1
)
SELECT is( count(*)::int, 0,
    'regular user DELETE on users affects 0 rows' ) FROM del;

-- 4. Confirm (as an admin) the attacked row was untouched.
SELECT authenticate_as('user3');  -- admin: has user:manage / user:read
SELECT isnt(
    (SELECT email FROM users WHERE external_id = 'user2'),
    'hacked@evil.com',
    'user2 email is unchanged after the regular-user write attempts'
);

-- 5. Positive control: an admin CAN update users.
WITH upd AS (
    UPDATE users SET email = email WHERE external_id = 'user2' RETURNING 1
)
SELECT is( count(*)::int, 1,
    'admin (user:manage) can UPDATE users' ) FROM upd;

-- =====================================================
-- PART 2: No escalation through the RBAC tables
-- =====================================================
-- Test (PIN, expected GREEN): a non-admin cannot escalate by writing the RBAC tables.
--
-- The stage-2 panel checked these and found them correctly forbidden (the RBAC tables are
-- admin-gated via RLS WITH CHECK, generated by create_entity_policies in
-- 0160_dd_functions.sql), but UNTESTED — so this pins invariant
-- I5 (no privilege escalation) against regression. Unlike 0610/0620 these should PASS now.
--
-- Fixtures: user1=1001 (plain user, holds the User role = role 1), user3=admin.

RESET ROLE;
SET LOCAL search_path TO public, pgtap;

-- Stash valid keys as admin so each attempt below fails ONLY on RLS (42501), not on a bad FK.
-- The permission key is its name, so that one is a literal.
SELECT authenticate_as('user3');
CREATE TEMP TABLE _esc AS
SELECT
    (SELECT id FROM roles       WHERE role_name       = 'Administrator') AS admin_role,
    (SELECT id FROM roles       WHERE role_name       = 'User')          AS user_role,
    'admin'::text                                                        AS admin_perm;

-- =====================================================
-- As user1 (non-admin): every self-grant path must be rejected by RLS (42501).
-- =====================================================
SELECT authenticate_as('user1');

-- 1. Self-assign the Administrator role via user_roles.
SELECT throws_ok(
    $$ INSERT INTO user_roles (user_id, role_id)
       VALUES (1001, (SELECT admin_role FROM _esc)) $$,
    '42501', NULL,
    'I5: user1 cannot self-grant Administrator via user_roles'
);

-- 2. Self-grant the admin permission directly via user_permissions.
SELECT throws_ok(
    $$ INSERT INTO user_permissions (user_id, permission_name)
       VALUES (1001, (SELECT admin_perm FROM _esc)) $$,
    '42501', NULL,
    'I5: user1 cannot self-grant the admin permission via user_permissions'
);

-- 3. Grant the admin permission to the User role (which user1 holds) via role_permissions.
SELECT throws_ok(
    $$ INSERT INTO role_permissions (role_id, permission_name)
       VALUES ((SELECT user_role FROM _esc), (SELECT admin_perm FROM _esc)) $$,
    '42501', NULL,
    'I5: user1 cannot grant admin to the User role via role_permissions'
);

-- 4. Insert a brand-new permission (which would auto-grant to Administrator).
SELECT throws_ok(
    $$ INSERT INTO permissions (permission_name, description, module_id)
       VALUES ('evil:escalate', 'should be rejected', 1) $$,
    '42501', NULL,
    'I5: user1 cannot create a permission'
);

SELECT * FROM finish();
ROLLBACK;
