/**
 * @semantius/triggerdev - Migrate function
 *
 * Executes Semantius database migrations from within a TriggerDev task.
 * Uses pre-bundled SQL content (generated by `deno task bundle-sql`) instead
 * of reading from the filesystem, making it suitable for serverless/edge
 * deployment environments like TriggerDev.
 *
 * Setup instructions:
 *
 * 1. Install dependencies:
 *    pnpm add @semantius/triggerdev
 *
 * 2. Bundle SQL files (run from project root before deploying):
 *    deno task bundle-sql
 *    # or: pnpm run bundle-sql
 *
 * 3. Use in a TriggerDev task:
 *    import { task } from "@trigger.dev/sdk/v3";
 *    import { migrate } from "@semantius/triggerdev";
 *
 *    export const migrationTask = task({
 *      id: "run-migrations",
 *      run: async (payload: { modules?: string[] }) => {
 *        await migrate(process.env.DATABASE_URL!, payload.modules);
 *      },
 *    });
 *
 * 4. Trigger the task from your application code:
 *    import { tasks } from "@trigger.dev/sdk/v3";
 *    await tasks.trigger("run-migrations", { modules: ["_core", "nwind"] });
 */

import { Client, type ClientConfig } from "pg";
import {
  ensureVersionsTable,
  executeMigrations,
  type MigrationFile,
} from "@semantius/core";
import {
  getBundledAppNames,
  getBundledMigrations,
} from "./migrations-bundle.js";

export interface MigrateOptions {
  /** If true, enables verbose logging. Defaults to false. */
  verbose?: boolean;
}

/**
 * Runs database migrations for the specified modules using bundled SQL content.
 *
 * @param databaseUrl  PostgreSQL connection URL (e.g. postgresql://user:pass@host/db)
 * @param modules      List of module/app names to migrate.
 *                     Defaults to all bundled apps if not provided.
 *                     The "_core" module is always prepended automatically.
 * @param options      Optional configuration (verbose logging, etc.)
 */
export async function migrate(
  databaseUrl: string,
  modules?: string[],
  options: MigrateOptions = {},
): Promise<void> {
  const { verbose = false } = options;

  const log = (msg: string) => console.log(`[semantius/triggerdev] ${msg}`);
  const logVerbose = (msg: string) => {
    if (verbose) log(msg);
  };

  log("Starting migration...");

  // Determine which apps to migrate
  let appsToMigrate: string[];
  if (!modules || modules.length === 0) {
    appsToMigrate = getBundledAppNames();
    logVerbose(
      `No modules specified - using all bundled apps: ${appsToMigrate.join(", ")}`,
    );
  } else {
    // Always ensure _core is first
    const withoutCore = modules.filter((m) => m !== "_core");
    appsToMigrate = ["_core", ...withoutCore];
    logVerbose(`Modules to migrate: ${appsToMigrate.join(", ")}`);
  }

  // Connect with advisory lock to prevent concurrent migrations
  const clientConfig: ClientConfig = { connectionString: databaseUrl };
  const lockClient = new Client(clientConfig);

  try {
    await lockClient.connect();
    logVerbose("Connected to database");

    const lockResult = await lockClient.query(
      "SELECT pg_try_advisory_lock(hashtext('migrate')) AS acquired",
    );
    const lockAcquired = lockResult.rows[0]?.acquired as boolean;

    if (!lockAcquired) {
      throw new Error(
        "Failed to acquire migration lock. Another migration may already be running.",
      );
    }

    logVerbose("Migration lock acquired");

    try {
      for (const appName of appsToMigrate) {
        const migrations = getBundledMigrations(appName);

        if (migrations.length === 0) {
          log(`No bundled migrations found for app: ${appName} - skipping`);
          continue;
        }

        log(`Migrating app: ${appName} (${migrations.length} file(s))`);
        await migrateApp(appName, migrations, databaseUrl, verbose);
        log(`Completed: ${appName}`);
      }

      log("All migrations completed successfully.");
    } finally {
      try {
        await lockClient.query(
          "SELECT pg_advisory_unlock(hashtext('migrate'))",
        );
        logVerbose("Migration lock released");
      } catch (unlockError) {
        console.error(
          "[semantius/triggerdev] Warning: failed to release migration lock:",
          unlockError instanceof Error
            ? unlockError.message
            : String(unlockError),
        );
      }
    }
  } finally {
    try {
      await lockClient.end();
      logVerbose("Lock client connection closed");
    } catch {
      // ignore close errors
    }
  }
}

async function migrateApp(
  appName: string,
  migrations: MigrationFile[],
  databaseUrl: string,
  verbose: boolean,
): Promise<void> {
  const clientConfig: ClientConfig = { connectionString: databaseUrl };
  const client = new Client(clientConfig);

  const logVerbose = (msg: string) => {
    if (verbose) console.log(`[semantius/triggerdev] ${msg}`);
  };

  // Wrap pg Client to match the DatabaseClient interface expected by core
  const dbClient = {
    queryObject: async (
      sql: string,
      params?: unknown[],
    ): Promise<{ rows: Record<string, unknown>[] }> => {
      const result = await client.query(sql, params as unknown[]);
      return { rows: result.rows as Record<string, unknown>[] };
    },
  };

  try {
    await client.connect();
    logVerbose(`Connected to database for app: ${appName}`);

    await ensureVersionsTable(dbClient);
    await executeMigrations(appName, migrations, dbClient);
  } catch (error) {
    if (error instanceof Error) {
      if (error.message.includes("authentication failed")) {
        throw new Error(
          `Authentication failed for ${appName}. Check your DATABASE_URL credentials.`,
        );
      } else if (
        error.message.includes("database") &&
        error.message.includes("does not exist")
      ) {
        throw new Error(
          `Database does not exist for ${appName}. Check the database name in DATABASE_URL.`,
        );
      } else if (error.message.includes("ECONNREFUSED")) {
        throw new Error(
          `Connection refused for ${appName}. Is the database server running?`,
        );
      } else if (error.message.includes("SSL")) {
        throw new Error(
          `SSL connection error for ${appName}. Check SSL configuration in DATABASE_URL.`,
        );
      } else {
        throw new Error(
          `Migration failed for ${appName}: ${error.message}`,
        );
      }
    }
    throw error;
  } finally {
    try {
      await client.end();
      logVerbose(`Connection closed for app: ${appName}`);
    } catch {
      // ignore close errors
    }
  }
}

export { getBundledAppNames, getBundledMigrations } from "./migrations-bundle.js";
export type { MigrationFile } from "@semantius/core";
