/**
 * @semantius/triggerdev - Migrate function
 *
 * Executes Semantius database migrations from within a TriggerDev task.
 * Uses pre-bundled SQL content (generated by `deno task bundle-sql`) instead
 * of reading from the filesystem, making it suitable for serverless/edge
 * deployment environments like TriggerDev.
 *
 * Setup instructions:
 *
 * 1. Install dependencies:
 *    pnpm add @semantius/triggerdev
 *
 * 2. Bundle SQL files (run from project root before deploying):
 *    deno task bundle-sql
 *    # or: pnpm run bundle-sql
 *
 * 3. Use in a TriggerDev task:
 *    import { task } from "@trigger.dev/sdk/v3";
 *    import { migrate } from "@semantius/triggerdev";
 *
 *    export const migrationTask = task({
 *      id: "run-migrations",
 *      run: async (payload: { modules?: string[] }) => {
 *        await migrate(process.env.DATABASE_URL!, payload.modules);
 *      },
 *    });
 *
 * 4. Trigger the task from your application code:
 *    import { tasks } from "@trigger.dev/sdk/v3";
 *    await tasks.trigger("run-migrations", { modules: ["_core", "nwind"] });
 */

import { Client, type ClientConfig } from "pg";
import { type AppMigrations, runMigrations } from "@semantius/core";
import {
  getBundledAppNames,
  getBundledMigrations,
} from "./migrations-bundle.js";

export interface MigrateOptions {
  /** If true, enables verbose logging. Defaults to false. */
  verbose?: boolean;
}

/**
 * Runs database migrations for the specified modules using bundled SQL content.
 *
 * @param databaseUrl  PostgreSQL connection URL (e.g. postgresql://user:pass@host/db)
 * @param modules      List of module/app names to migrate.
 *                     Defaults to all bundled apps if not provided.
 *                     The "_core" module is always prepended automatically.
 * @param options      Optional configuration (verbose logging, etc.)
 */
export async function migrate(
  databaseUrl: string,
  modules?: string[],
  options: MigrateOptions = {},
): Promise<void> {
  const { verbose = false } = options;

  const log = (msg: string) => console.log(`[semantius/triggerdev] ${msg}`);
  const logVerbose = (msg: string) => {
    if (verbose) log(msg);
  };

  log("Starting migration...");

  // Determine which apps to migrate
  let appsToMigrate: string[];
  if (!modules || modules.length === 0) {
    appsToMigrate = getBundledAppNames();
    logVerbose(
      `No modules specified - using all bundled apps: ${appsToMigrate.join(", ")}`,
    );
  } else {
    // Always ensure _core is first
    const withoutCore = modules.filter((m) => m !== "_core");
    appsToMigrate = ["_core", ...withoutCore];
    logVerbose(`Modules to migrate: ${appsToMigrate.join(", ")}`);
  }

  // One connection for the whole pass: the migration lock is a session lock,
  // and every file's ledger row must be read under it.
  const clientConfig: ClientConfig = { connectionString: databaseUrl };
  const client = new Client(clientConfig);

  // Wrap pg Client to match the DatabaseClient interface expected by core
  const dbClient = {
    queryObject: async (
      sql: string,
      params?: unknown[],
    ): Promise<{ rows: Record<string, unknown>[] }> => {
      const result = await client.query(sql, params as unknown[]);
      return { rows: result.rows as Record<string, unknown>[] };
    },
  };

  const apps: AppMigrations[] = [];
  for (const appName of appsToMigrate) {
    const migrations = getBundledMigrations(appName);
    if (migrations.length === 0) {
      log(`No bundled migrations found for app: ${appName} - skipping`);
      continue;
    }
    log(`Migrating app: ${appName} (${migrations.length} file(s))`);
    apps.push({ app: appName, migrations });
  }

  try {
    await client.connect();
    logVerbose("Connected to database");
    const result = await runMigrations(dbClient, apps);
    log(
      `All migrations completed successfully (${result.applied} applied, ${result.skipped} skipped).`,
    );
  } catch (error) {
    if (error instanceof Error) {
      if (error.message.includes("authentication failed")) {
        throw new Error(
          "Authentication failed. Check your DATABASE_URL credentials.",
        );
      } else if (
        error.message.includes("database") &&
        error.message.includes("does not exist")
      ) {
        throw new Error(
          "Database does not exist. Check the database name in DATABASE_URL.",
        );
      } else if (error.message.includes("ECONNREFUSED")) {
        throw new Error(
          "Connection refused. Is the database server running?",
        );
      } else if (error.message.includes("SSL")) {
        throw new Error(
          "SSL connection error. Check SSL configuration in DATABASE_URL.",
        );
      }
    }
    throw error;
  } finally {
    try {
      await client.end();
      logVerbose("Connection closed");
    } catch {
      // ignore close errors
    }
  }
}

export { getBundledAppNames, getBundledMigrations } from "./migrations-bundle.js";
export type { MigrationFile } from "@semantius/core";
