// =============================================================================
// list-users.ts — list users from a Semantic Platform database with Drizzle,
// authenticating via an OAuth token from the test OIDC server (PostgreSQL 18
// SASL OAUTHBEARER). The first Drizzle sample; sibling files add more (count,
// joins, …).
// =============================================================================
//
// Drizzle is schema-first, so it uses the schema generated from the catalog
// (`deno task drizzlegen`) and runs over the OAUTHBEARER transport through
// `drizzle-orm/pg-proxy` (see ./drizzle-proxy).
//
// What it does, end to end:
//   1. Get an access token (./get-auth-token — mints a test token here; in a
//      real app you'd return the current user's session token instead).
//   2. Connect to PostgreSQL as the `authenticated` role, presenting that token
//      over SASL OAUTHBEARER (./pg-oauthbearer).
//   3. Call public.get_userinfo() once — first-login provisioning. It assigns the
//      `User` role (user:read); the RLS SELECT policy on `users` needs it, so
//      without this the list would come back empty.
//   4. Run a typed Drizzle `select … from users` and print the rows under RLS.
//
// The connection probe and the provisioning call use the raw transport directly:
// `db.execute(sql\`…\`)` over pg-proxy returns positional arrays with no column
// names to map them to, whereas a Drizzle `.select()` maps cleanly because
// Drizzle generated the column order itself. So we use raw SQL for the two
// bookkeeping calls and Drizzle for the headline query.
//
// Run it (from this folder):
//   npm install
//   npx tsx src/list-users.ts   # run this sample
//   npm start                   # convenience alias for this first sample
//
// Env vars (defaults in parentheses):
//   PGHOST (localhost)  PGPORT (5432)  PGDATABASE (appdb)
//   USER_ID (user3 = admin@test.com)  CLIENT_ID (test-client)  ISSUER (https://oidc-test.semanti.us)
//   (USER_ID / CLIENT_ID / ISSUER are read by ./get-auth-token.)
//
// For the EXTENSION stack (pg-ext-*), use PGPORT=5433. The CLI stack (5432) needs
// `_core` deployed first (deno task migrate --apps _core). Either way the
// container must be able to reach the issuer's HTTPS JWKS endpoint outbound.
// =============================================================================

import { PgOAuthConnection } from "./pg-oauthbearer";
import { getAuthToken } from "./get-auth-token";
import { createDb } from "./drizzle-proxy";
import { users } from "./schema";

const HOST = process.env.PGHOST ?? "localhost";
const PORT = Number(process.env.PGPORT ?? 5432);
const DATABASE = process.env.PGDATABASE ?? "appdb";
const USER_ID = process.env.USER_ID ?? "user3"; // for the summary line only (user3 = admin@test.com)

async function main(): Promise<void> {
  const token = await getAuthToken();

  const conn = await PgOAuthConnection.connect({
    host: HOST,
    port: PORT,
    database: DATABASE,
    token,
  });

  try {
    // Prove who we are on the wire (raw transport — see header note).
    // `system_user` is `oauth:<sub>`: the identity PostgreSQL validated from the
    // bearer token against the issuer's JWKS; a client cannot forge it.
    const who = await conn.query("select current_user, system_user");
    const whoRow = Object.fromEntries(
      who.fields.map((name, i) => [name, who.rows[0]?.[i]]),
    );
    console.log("Connected:", whoRow);

    // First-login provisioning (assigns the User role -> user:read).
    await conn.query("select public.get_userinfo()");

    // The goal: a typed list of users via Drizzle, returned under RLS.
    const db = createDb(conn);
    const rows = await db
      .select({
        id: users.id,
        externalId: users.externalId,
        email: users.email,
        displayName: users.displayName,
        lastSeen: users.lastSeen,
      })
      .from(users)
      .orderBy(users.id);

    console.log();
    console.table(rows);
    console.log(`\n${rows.length} user(s) visible to "${USER_ID}" under RLS.`);

    // ── Bonus: the relational query API (relations generated by drizzlegen) ──
    // List each visible user together with the roles assigned to them. The
    // relation field names come from the generated schema (admin.ts):
    //
    //   const withRoles = await db.query.users.findMany({
    //     columns: { id: true, email: true },
    //     with: { userRolesUser: { with: { role: true } } },
    //   });
    //   console.dir(withRoles, { depth: null });
  } finally {
    await conn.end();
  }
}

main().catch((err) => {
  console.error("FAILED:", err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
