// AUTO-GENERATED by `deno task drizzlegen`. Do not edit by hand.

import { bigserial, boolean, integer, jsonb, pgTable, serial, text, timestamp, uuid } from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

export const auditDdlLogs = pgTable("audit_ddl_logs", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  eventTime: timestamp("event_time", { withTimezone: true }),
  userId: integer("user_id").notNull(),
  commandTag: text("command_tag").notNull(),
  objectType: text("object_type").notNull(),
  objectIdentity: text("object_identity").notNull(),
  queryText: text("query_text").notNull(),
});

export const auditRecordLogs = pgTable("audit_record_logs", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  recordId: uuid("record_id").notNull(),
  oldRecordId: uuid("old_record_id").notNull(),
  recordPk: text("record_pk").notNull(),
  op: text("op").notNull(),
  ts: timestamp("ts", { withTimezone: true }),
  userId: integer("user_id").notNull(),
  tableOid: integer("table_oid").notNull(),
  tableSchema: text("table_schema").notNull(),
  tableName: text("table_name").notNull(),
  record: jsonb("record").notNull(),
  oldRecord: jsonb("old_record").notNull(),
});

export const dashboards = pgTable("dashboards", {
  id: serial("id").primaryKey(),
  config: jsonb("config").notNull(),
  position: integer("position").notNull().default(0),
  label: text("label").notNull(),
  moduleId: integer("module_id").references((): AnyPgColumn => modules.id, { onDelete: "cascade" }),
  viewPermission: text("view_permission").references((): AnyPgColumn => permissions.permissionName, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const entities = pgTable("entities", {
  tableName: text("table_name").primaryKey(),
  singular: text("singular").notNull(),
  plural: text("plural").notNull(),
  singularLabel: text("singular_label").notNull(),
  pluralLabel: text("plural_label").notNull(),
  iconUrl: text("icon_url").notNull(),
  description: text("description").notNull(),
  moduleId: integer("module_id").references((): AnyPgColumn => modules.id, { onDelete: "cascade" }),
  viewPermission: text("view_permission").references((): AnyPgColumn => permissions.permissionName),
  editPermission: text("edit_permission").references((): AnyPgColumn => permissions.permissionName),
  idColumn: text("id_column").notNull().default("id"),
  labelColumn: text("label_column").notNull().default("label"),
  labelParent: text("label_parent").notNull(),
  orderColumn: text("order_column").notNull(),
  managed: boolean("managed").notNull().default(true),
  searchable: boolean("searchable").notNull(),
  isChild: boolean("is_child").notNull(),
  editMode: text("edit_mode", { enum: ["auto", "sidebar", "modal", "page", ""] }).notNull().default("auto"),
  cubeMode: text("cube_mode", { enum: ["disabled", "auto", ""] }).notNull().default("auto"),
  entityType: text("entity_type", { enum: ["operational_workflow", "operational_record", "catalog", "junction", "computed", "unclassified", ""] }).notNull().default("unclassified"),
  auditLog: boolean("audit_log").notNull().default(false),
  computedFields: jsonb("computed_fields").notNull(),
  validationRules: jsonb("validation_rules").notNull(),
  selectRule: jsonb("select_rule").notNull(),
  catalogEntityCode: text("catalog_entity_code").notNull(),
  catalogOwnerModule: text("catalog_owner_module").notNull(),
  catalogEntityAliases: jsonb("catalog_entity_aliases").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const fields = pgTable("fields", {
  id: text("id").primaryKey(),
  tableName: text("table_name").references((): AnyPgColumn => entities.tableName, { onDelete: "cascade" }).notNull(),
  fieldName: text("field_name").notNull(),
  format: text("format", { enum: ["json", "html", "text", "multiline", "code", "jsonata", "reference", "parent", "enum", "date", "time", "date-time", "duration", "uri", "uri-reference", "uri-template", "url", "email", "hostname", "ipv4", "ipv6", "regex", "uuid", "json-pointer", "json-pointer-uri-fragment", "relative-json-pointer", "byte", "int32", "int64", "float", "double", "password", "binary", "string", "number", "integer", "boolean", "object", "array", "null"] }).notNull().default("text"),
  title: text("title").notNull(),
  description: text("description").notNull(),
  isPk: boolean("is_pk").notNull(),
  defaultValue: text("default_value").notNull(),
  fieldOrder: integer("field_order").notNull(),
  inputType: text("input_type", { enum: ["default", "required", "readonly", "disabled", "hidden"] }).notNull().default("default"),
  width: text("width", { enum: ["default", "s", "m", "w"] }).notNull().default("default"),
  ctype: text("ctype", { enum: ["", "id", "label", "audit", "core"] }).notNull(),
  searchable: boolean("searchable").notNull(),
  enumValues: jsonb("enum_values").notNull(),
  precision: integer("precision").notNull().default(2),
  referenceTable: text("reference_table").notNull(),
  referenceDeleteMode: text("reference_delete_mode", { enum: ["", "restrict", "clear", "cascade"] }).notNull().default("restrict"),
  relationshipLabel: text("relationship_label").notNull().default("has"),
  singularLabelParent: text("singular_label_parent").notNull(),
  pluralLabelParent: text("plural_label_parent").notNull(),
  uniqueValue: boolean("unique_value").notNull(),
  cubeType: text("cube_type", { enum: ["auto", "dimension", "measure", "disabled"] }).notNull().default("auto"),
  inputTypeRule: jsonb("input_type_rule").notNull(),
  catalogFieldCode: text("catalog_field_code").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const modules = pgTable("modules", {
  id: serial("id").primaryKey(),
  moduleName: text("module_name").notNull(),
  description: text("description").notNull(),
  moduleType: text("module_type", { enum: ["domain", "master", ""] }).notNull(),
  viewPermission: text("view_permission").references((): AnyPgColumn => permissions.permissionName),
  logoColor: text("logo_color").notNull(),
  iconName: text("icon_name").notNull(),
  moduleSlug: text("module_slug").notNull(),
  homePage: text("home_page").notNull(),
  managePermission: text("manage_permission").references((): AnyPgColumn => permissions.permissionName, { onDelete: "set null" }),
  adminPermission: text("admin_permission").references((): AnyPgColumn => permissions.permissionName, { onDelete: "set null" }),
  defaultViewerRoleId: integer("default_viewer_role_id").references((): AnyPgColumn => roles.id, { onDelete: "set null" }),
  defaultManagerRoleId: integer("default_manager_role_id").references((): AnyPgColumn => roles.id, { onDelete: "set null" }),
  defaultAdminRoleId: integer("default_admin_role_id").references((): AnyPgColumn => roles.id, { onDelete: "set null" }),
  catalogModuleCode: text("catalog_module_code").notNull(),
  domainCode: text("domain_code").notNull(),
  accessScope: text("access_scope", { enum: ["basic", "full", ""] }).notNull(),
  settings: jsonb("settings").notNull(),
  dashboardConfig: jsonb("dashboard_config").notNull(),
  version: integer("version").notNull(),
  versionDate: timestamp("version_date", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const permissionHierarchy = pgTable("permission_hierarchy", {
  id: text("id").primaryKey(),
  includingPermissionName: text("including_permission_name").references((): AnyPgColumn => permissions.permissionName, { onDelete: "cascade" }).notNull(),
  includedPermissionName: text("included_permission_name").references((): AnyPgColumn => permissions.permissionName, { onDelete: "cascade" }).notNull(),
  origin: text("origin", { enum: ["system", "model", "model_master", "user", ""] }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const permissions = pgTable("permissions", {
  permissionName: text("permission_name").primaryKey(),
  description: text("description").notNull(),
  moduleId: integer("module_id").references((): AnyPgColumn => modules.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const processGates = pgTable("process_gates", {
  name: text("name").notNull(),
  id: serial("id").primaryKey(),
  processId: integer("process_id").references((): AnyPgColumn => processes.id, { onDelete: "cascade" }).notNull(),
  entity: text("entity").notNull(),
  gateKind: text("gate_kind", { enum: ["approval", "submit_lock", "ownership", "create", "transition"] }).notNull(),
  toState: text("to_state").notNull(),
  stateColumn: text("state_column").notNull().default("status"),
  emitsEvents: boolean("emits_events").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const processes = pgTable("processes", {
  name: text("name").notNull(),
  id: serial("id").primaryKey(),
  moduleId: integer("module_id").references((): AnyPgColumn => modules.id, { onDelete: "set null" }),
  processKey: text("process_key").notNull(),
  description: text("description").notNull(),
  ordering: integer("ordering").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const queueTableEvents = pgTable("queue_table_events", {
  queueId: integer("queue_id").references((): AnyPgColumn => queues.id, { onDelete: "cascade" }).notNull(),
  tableName: text("table_name").references((): AnyPgColumn => entities.tableName, { onDelete: "cascade" }),
  id: serial("id").primaryKey(),
  eventHandler: text("event_handler", { enum: ["insert", "update", "upsert", "delete", "change"] }).notNull(),
  eventName: text("event_name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const queues = pgTable("queues", {
  id: serial("id").primaryKey(),
  queueName: text("queue_name").notNull(),
  viewPermission: text("view_permission").references((): AnyPgColumn => permissions.permissionName),
  managePermission: text("manage_permission").references((): AnyPgColumn => permissions.permissionName),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const raciAssignments = pgTable("raci_assignments", {
  name: text("name").notNull(),
  id: serial("id").primaryKey(),
  processId: integer("process_id").references((): AnyPgColumn => processes.id, { onDelete: "cascade" }).notNull(),
  roleId: integer("role_id").references((): AnyPgColumn => roles.id, { onDelete: "cascade" }),
  raci: text("raci", { enum: ["responsible", "accountable", "consulted", "informed"] }).notNull(),
  consultMode: text("consult_mode", { enum: ["read", "notify", "block", ""] }).notNull().default("read"),
  origin: text("origin", { enum: ["system", "user", ""] }).notNull().default("user"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const raciEvents = pgTable("raci_events", {
  processId: integer("process_id").references((): AnyPgColumn => processes.id, { onDelete: "cascade" }).notNull(),
  id: serial("id").primaryKey(),
  entity: text("entity").notNull(),
  recordId: text("record_id").notNull(),
  raci: text("raci", { enum: ["consulted", "informed"] }).notNull(),
  targetRoleId: integer("target_role_id").references((): AnyPgColumn => roles.id, { onDelete: "cascade" }),
  status: text("status", { enum: ["pending", "sent", "acted"] }).notNull().default("pending"),
  actedAt: timestamp("acted_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const rolePermissions = pgTable("role_permissions", {
  id: text("id").primaryKey(),
  roleId: integer("role_id").references((): AnyPgColumn => roles.id, { onDelete: "cascade" }).notNull(),
  permissionName: text("permission_name").references((): AnyPgColumn => permissions.permissionName, { onDelete: "cascade" }).notNull(),
  grantedAt: timestamp("granted_at", { withTimezone: true }),
  grantedBy: integer("granted_by").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
});

export const roles = pgTable("roles", {
  id: serial("id").primaryKey(),
  roleName: text("role_name").notNull(),
  slug: text("slug").notNull(),
  catalogRoleCode: text("catalog_role_code").notNull(),
  description: text("description").notNull(),
  origin: text("origin", { enum: ["system", "model", "model_master", "user", ""] }).notNull(),
  moduleId: integer("module_id").references((): AnyPgColumn => modules.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const userBookmarks = pgTable("user_bookmarks", {
  userId: integer("user_id").references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  url: text("url").notNull(),
  entityName: text("entity_name").notNull(),
  entityId: integer("entity_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const userPermissions = pgTable("user_permissions", {
  id: text("id").primaryKey(),
  userId: integer("user_id").references((): AnyPgColumn => users.id, { onDelete: "cascade" }).notNull(),
  permissionName: text("permission_name").references((): AnyPgColumn => permissions.permissionName, { onDelete: "cascade" }).notNull(),
  grantedAt: timestamp("granted_at", { withTimezone: true }),
  grantedBy: integer("granted_by").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
});

export const userRoles = pgTable("user_roles", {
  id: text("id").primaryKey(),
  userId: integer("user_id").references((): AnyPgColumn => users.id, { onDelete: "cascade" }).notNull(),
  roleId: integer("role_id").references((): AnyPgColumn => roles.id, { onDelete: "cascade" }).notNull(),
  assignedAt: timestamp("assigned_at", { withTimezone: true }),
  assignedBy: integer("assigned_by").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
});

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  externalId: text("external_id").notNull(),
  email: text("email").notNull(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  displayName: text("display_name").notNull(),
  isDisabled: boolean("is_disabled").notNull(),
  settings: jsonb("settings").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  lastSeen: timestamp("last_seen", { withTimezone: true }),
  isAgent: boolean("is_agent").notNull().default(false),
});

export const webhookReceiverLogs = pgTable("webhook_receiver_logs", {
  webhookId: integer("webhook_id").references((): AnyPgColumn => webhookReceivers.id, { onDelete: "cascade" }).notNull(),
  webhookReceiverId: integer("webhook_receiver_id").references((): AnyPgColumn => webhookReceivers.id, { onDelete: "set null" }),
  id: serial("id").primaryKey(),
  label: text("label").notNull(),
  webhookTimestamp: timestamp("webhook_timestamp", { withTimezone: true }),
  receivedTimestamp: timestamp("received_timestamp", { withTimezone: true }),
  payload: jsonb("payload").notNull(),
  result: text("result", { enum: ["10", "20", "90", ""] }).notNull().default("10"),
  errorMessage: text("error_message").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const webhookReceivers = pgTable("webhook_receivers", {
  tableName: text("table_name").references((): AnyPgColumn => entities.tableName, { onDelete: "cascade" }),
  id: serial("id").primaryKey(),
  label: text("label").notNull(),
  description: text("description").notNull(),
  authType: text("auth_type", { enum: ["none", "hmac", "header", ""] }).notNull().default("none"),
  secret: text("secret").notNull(),
  headerName: text("header_name").notNull(),
  headerValue: text("header_value").notNull(),
  jsonata: text("jsonata").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const dashboardsRelations = relations(dashboards, ({ one }) => ({
  module: one(modules, { fields: [dashboards.moduleId], references: [modules.id], relationName: "dashboards_module_id" }),
  viewPermission: one(permissions, { fields: [dashboards.viewPermission], references: [permissions.permissionName], relationName: "dashboards_view_permission" }),
}));

export const entitiesRelations = relations(entities, ({ one, many }) => ({
  module: one(modules, { fields: [entities.moduleId], references: [modules.id], relationName: "entities_module_id" }),
  viewPermission: one(permissions, { fields: [entities.viewPermission], references: [permissions.permissionName], relationName: "entities_view_permission" }),
  editPermission: one(permissions, { fields: [entities.editPermission], references: [permissions.permissionName], relationName: "entities_edit_permission" }),
  fields: many(fields, { relationName: "fields_table_name" }),
  queueTableEvents: many(queueTableEvents, { relationName: "queue_table_events_table_name" }),
  webhookReceivers: many(webhookReceivers, { relationName: "webhook_receivers_table_name" }),
}));

export const fieldsRelations = relations(fields, ({ one }) => ({
  tableName: one(entities, { fields: [fields.tableName], references: [entities.tableName], relationName: "fields_table_name" }),
}));

export const modulesRelations = relations(modules, ({ one, many }) => ({
  viewPermission: one(permissions, { fields: [modules.viewPermission], references: [permissions.permissionName], relationName: "modules_view_permission" }),
  managePermission: one(permissions, { fields: [modules.managePermission], references: [permissions.permissionName], relationName: "modules_manage_permission" }),
  adminPermission: one(permissions, { fields: [modules.adminPermission], references: [permissions.permissionName], relationName: "modules_admin_permission" }),
  defaultViewerRole: one(roles, { fields: [modules.defaultViewerRoleId], references: [roles.id], relationName: "modules_default_viewer_role_id" }),
  defaultManagerRole: one(roles, { fields: [modules.defaultManagerRoleId], references: [roles.id], relationName: "modules_default_manager_role_id" }),
  defaultAdminRole: one(roles, { fields: [modules.defaultAdminRoleId], references: [roles.id], relationName: "modules_default_admin_role_id" }),
  dashboards: many(dashboards, { relationName: "dashboards_module_id" }),
  entities: many(entities, { relationName: "entities_module_id" }),
  permissions: many(permissions, { relationName: "permissions_module_id" }),
  processes: many(processes, { relationName: "processes_module_id" }),
  roles: many(roles, { relationName: "roles_module_id" }),
}));

export const permissionHierarchyRelations = relations(permissionHierarchy, ({ one }) => ({
  includingPermissionName: one(permissions, { fields: [permissionHierarchy.includingPermissionName], references: [permissions.permissionName], relationName: "permission_hierarchy_including_permission_name" }),
  includedPermissionName: one(permissions, { fields: [permissionHierarchy.includedPermissionName], references: [permissions.permissionName], relationName: "permission_hierarchy_included_permission_name" }),
}));

export const permissionsRelations = relations(permissions, ({ one, many }) => ({
  module: one(modules, { fields: [permissions.moduleId], references: [modules.id], relationName: "permissions_module_id" }),
  dashboards: many(dashboards, { relationName: "dashboards_view_permission" }),
  entitiesViewPermission: many(entities, { relationName: "entities_view_permission" }),
  entitiesEditPermission: many(entities, { relationName: "entities_edit_permission" }),
  modulesViewPermission: many(modules, { relationName: "modules_view_permission" }),
  modulesManagePermission: many(modules, { relationName: "modules_manage_permission" }),
  modulesAdminPermission: many(modules, { relationName: "modules_admin_permission" }),
  permissionHierarchyIncludingPermissionName: many(permissionHierarchy, { relationName: "permission_hierarchy_including_permission_name" }),
  permissionHierarchyIncludedPermissionName: many(permissionHierarchy, { relationName: "permission_hierarchy_included_permission_name" }),
  queuesViewPermission: many(queues, { relationName: "queues_view_permission" }),
  queuesManagePermission: many(queues, { relationName: "queues_manage_permission" }),
  rolePermissions: many(rolePermissions, { relationName: "role_permissions_permission_name" }),
  userPermissions: many(userPermissions, { relationName: "user_permissions_permission_name" }),
}));

export const processGatesRelations = relations(processGates, ({ one }) => ({
  process: one(processes, { fields: [processGates.processId], references: [processes.id], relationName: "process_gates_process_id" }),
}));

export const processesRelations = relations(processes, ({ one, many }) => ({
  module: one(modules, { fields: [processes.moduleId], references: [modules.id], relationName: "processes_module_id" }),
  processGates: many(processGates, { relationName: "process_gates_process_id" }),
  raciAssignments: many(raciAssignments, { relationName: "raci_assignments_process_id" }),
  raciEvents: many(raciEvents, { relationName: "raci_events_process_id" }),
}));

export const queueTableEventsRelations = relations(queueTableEvents, ({ one }) => ({
  queue: one(queues, { fields: [queueTableEvents.queueId], references: [queues.id], relationName: "queue_table_events_queue_id" }),
  tableName: one(entities, { fields: [queueTableEvents.tableName], references: [entities.tableName], relationName: "queue_table_events_table_name" }),
}));

export const queuesRelations = relations(queues, ({ one, many }) => ({
  viewPermission: one(permissions, { fields: [queues.viewPermission], references: [permissions.permissionName], relationName: "queues_view_permission" }),
  managePermission: one(permissions, { fields: [queues.managePermission], references: [permissions.permissionName], relationName: "queues_manage_permission" }),
  queueTableEvents: many(queueTableEvents, { relationName: "queue_table_events_queue_id" }),
}));

export const raciAssignmentsRelations = relations(raciAssignments, ({ one }) => ({
  process: one(processes, { fields: [raciAssignments.processId], references: [processes.id], relationName: "raci_assignments_process_id" }),
  role: one(roles, { fields: [raciAssignments.roleId], references: [roles.id], relationName: "raci_assignments_role_id" }),
}));

export const raciEventsRelations = relations(raciEvents, ({ one }) => ({
  process: one(processes, { fields: [raciEvents.processId], references: [processes.id], relationName: "raci_events_process_id" }),
  targetRole: one(roles, { fields: [raciEvents.targetRoleId], references: [roles.id], relationName: "raci_events_target_role_id" }),
}));

export const rolePermissionsRelations = relations(rolePermissions, ({ one }) => ({
  role: one(roles, { fields: [rolePermissions.roleId], references: [roles.id], relationName: "role_permissions_role_id" }),
  permissionName: one(permissions, { fields: [rolePermissions.permissionName], references: [permissions.permissionName], relationName: "role_permissions_permission_name" }),
  grantedBy: one(users, { fields: [rolePermissions.grantedBy], references: [users.id], relationName: "role_permissions_granted_by" }),
}));

export const rolesRelations = relations(roles, ({ one, many }) => ({
  module: one(modules, { fields: [roles.moduleId], references: [modules.id], relationName: "roles_module_id" }),
  modulesDefaultViewerRole: many(modules, { relationName: "modules_default_viewer_role_id" }),
  modulesDefaultManagerRole: many(modules, { relationName: "modules_default_manager_role_id" }),
  modulesDefaultAdminRole: many(modules, { relationName: "modules_default_admin_role_id" }),
  raciAssignments: many(raciAssignments, { relationName: "raci_assignments_role_id" }),
  raciEvents: many(raciEvents, { relationName: "raci_events_target_role_id" }),
  rolePermissions: many(rolePermissions, { relationName: "role_permissions_role_id" }),
  userRoles: many(userRoles, { relationName: "user_roles_role_id" }),
}));

export const userBookmarksRelations = relations(userBookmarks, ({ one }) => ({
  user: one(users, { fields: [userBookmarks.userId], references: [users.id], relationName: "user_bookmarks_user_id" }),
}));

export const userPermissionsRelations = relations(userPermissions, ({ one }) => ({
  user: one(users, { fields: [userPermissions.userId], references: [users.id], relationName: "user_permissions_user_id" }),
  permissionName: one(permissions, { fields: [userPermissions.permissionName], references: [permissions.permissionName], relationName: "user_permissions_permission_name" }),
  grantedBy: one(users, { fields: [userPermissions.grantedBy], references: [users.id], relationName: "user_permissions_granted_by" }),
}));

export const userRolesRelations = relations(userRoles, ({ one }) => ({
  user: one(users, { fields: [userRoles.userId], references: [users.id], relationName: "user_roles_user_id" }),
  role: one(roles, { fields: [userRoles.roleId], references: [roles.id], relationName: "user_roles_role_id" }),
  assignedBy: one(users, { fields: [userRoles.assignedBy], references: [users.id], relationName: "user_roles_assigned_by" }),
}));

export const usersRelations = relations(users, ({ many }) => ({
  rolePermissions: many(rolePermissions, { relationName: "role_permissions_granted_by" }),
  userBookmarks: many(userBookmarks, { relationName: "user_bookmarks_user_id" }),
  userPermissionsUser: many(userPermissions, { relationName: "user_permissions_user_id" }),
  userPermissionsGrantedBy: many(userPermissions, { relationName: "user_permissions_granted_by" }),
  userRolesUser: many(userRoles, { relationName: "user_roles_user_id" }),
  userRolesAssignedBy: many(userRoles, { relationName: "user_roles_assigned_by" }),
}));

export const webhookReceiverLogsRelations = relations(webhookReceiverLogs, ({ one }) => ({
  webhook: one(webhookReceivers, { fields: [webhookReceiverLogs.webhookId], references: [webhookReceivers.id], relationName: "webhook_receiver_logs_webhook_id" }),
  webhookReceiver: one(webhookReceivers, { fields: [webhookReceiverLogs.webhookReceiverId], references: [webhookReceivers.id], relationName: "webhook_receiver_logs_webhook_receiver_id" }),
}));

export const webhookReceiversRelations = relations(webhookReceivers, ({ one, many }) => ({
  tableName: one(entities, { fields: [webhookReceivers.tableName], references: [entities.tableName], relationName: "webhook_receivers_table_name" }),
  webhookReceiverLogsWebhook: many(webhookReceiverLogs, { relationName: "webhook_receiver_logs_webhook_id" }),
  webhookReceiverLogsWebhookReceiver: many(webhookReceiverLogs, { relationName: "webhook_receiver_logs_webhook_receiver_id" }),
}));
